### ISSUE TITLE
Stack level too deep with auto_instrument

### ISSUE THREAD

**Issue by gingerlime** [DataDog/dd-trace-rb#1338]
setting our Gemfile to

```
gem 'ddtrace', require: 'ddtrace/auto_instrument'
```

Seems to cause an infinite loop somewhere, causing "Stack level too deep". Possibly in combination with the rack-mini-profiler gem.

```
[root@stage.app.com] out: W, [2021-02-01T12:02:18.112123 #27757]  WARN -- ddtrace: [ddtrace] DATADOG TRACER DIAGNOSTIC - Agent Error: Datadog::Transport::InternalErrorResponse ok?: unsupported?:, not_found?:, client_error?:, server_error?:, internal_error?:true, payload:, error_type:Errno::ECONNREFUSED error:Failed to open TCP connection to 127.0.0.1:8126 (Connection refused - connect(2) for "127.0.0.1" port 8126) 00:33
[root@stage.app.com] out: #<Thread:0x000056429311e028@/var/local/app/new/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/workers.rb:72 run> terminated with exception (report_on_exception is true): 00:33
[root@stage.app.com] out: Traceback (most recent call last): 00:33
[root@stage.app.com] out: 	9363: from /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/workers.rb:72:in `block (2 levels) in start' 00:33
[root@stage.app.com] out: 	9362: from /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/workers.rb:106:in `perform' 00:33
[root@stage.app.com] out: 	9361: from /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/workers.rb:106:in `loop' 00:33
[root@stage.app.com] out: 	9360: from /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/workers.rb:107:in `block in perform' 00:33
[root@stage.app.com] out: 	9359: from /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/workers.rb:55:in `callback_traces' 00:33
[root@stage.app.com] out: 	9358: from /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/writer.rb:68:in `block in start_worker' 00:33
[root@stage.app.com] out: 	9357: from /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/writer.rb:109:in `send_spans' 00:33
[root@stage.app.com] out: 	9356: from /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/transport/traces.rb:126:in `send_traces' 00:33
[root@stage.app.com] out: 	 ... 9351 levels... 00:33
[root@stage.app.com] out: 	   4: from /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/configuration/options.rb:72:in `get_option' 00:33
[root@stage.app.com] out: 	   3: from /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/configuration/option.rb:27:in `get' 00:33
[root@stage.app.com] out: 	   2: from /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/configuration/option.rb:60:in `context_eval' 00:33
[root@stage.app.com] out: 	   1: from /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/configuration/option.rb:60:in `instance_eval' 00:33
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/contrib/configuration/settings.rb:15:in `block (2 levels) in <class:Settings>': stack level too deep (SystemStackError) 00:33
[root@stage.app.com] out: rake aborted! 00:43
[root@stage.app.com] out: SystemStackError: stack level too deep 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/contrib/configuration/settings.rb:15:in `block (2 levels) in <class:Settings>' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/configuration/option.rb:60:in `instance_eval' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/configuration/option.rb:60:in `context_eval' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/configuration/option.rb:27:in `get' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/configuration/options.rb:72:in `get_option' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/configuration/options.rb:43:in `block in default_helpers' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/contrib/configuration/settings.rb:30:in `[]' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/contrib/http/instrumentation.rb:116:in `datadog_pin' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/contrib/http/instrumentation.rb:38:in `request' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/rack-mini-profiler-2.3.1/lib/patches/net_patches.rb:19:in `block in request_with_mini_profiler' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/rack-mini-profiler-2.3.1/lib/mini_profiler/profiling_methods.rb:46:in `step' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/rack-mini-profiler-2.3.1/lib/patches/net_patches.rb:18:in `request_with_mini_profiler' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/contrib/http/instrumentation.rb:42:in `request' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/rack-mini-profiler-2.3.1/lib/patches/net_patches.rb:19:in `block in request_with_mini_profiler' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/rack-mini-profiler-2.3.1/lib/mini_profiler/profiling_methods.rb:46:in `step' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/rack-mini-profiler-2.3.1/lib/patches/net_patches.rb:18:in `request_with_mini_profiler' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/contrib/http/instrumentation.rb:42:in `request' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/rack-mini-profiler-2.3.1/lib/patches/net_patches.rb:19:in `block in request_with_mini_profiler' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/rack-mini-profiler-2.3.1/lib/mini_profiler/profiling_methods.rb:46:in `step' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/rack-mini-profiler-2.3.1/lib/patches/net_patches.rb:18:in `request_with_mini_profiler' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/contrib/http/instrumentation.rb:42:in `request' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/rack-mini-profiler-2.3.1/lib/patches/net_patches.rb:19:in `block in request_with_mini_profiler' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/rack-mini-profiler-2.3.1/lib/mini_profiler/profiling_methods.rb:46:in `step' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/rack-mini-profiler-2.3.1/lib/patches/net_patches.rb:18:in `request_with_mini_profiler' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/contrib/http/instrumentation.rb:42:in `request' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/rack-mini-profiler-2.3.1/lib/patches/net_patches.rb:19:in `block in request_with_mini_profiler' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/rack-mini-profiler-2.3.1/lib/mini_profiler/profiling_methods.rb:46:in `step' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/rack-mini-profiler-2.3.1/lib/patches/net_patches.rb:18:in `request_with_mini_profiler' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/contrib/http/instrumentation.rb:42:in `request' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/rack-mini-profiler-2.3.1/lib/patches/net_patches.rb:19:in `block in request_with_mini_profiler' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/rack-mini-profiler-2.3.1/lib/mini_profiler/profiling_methods.rb:46:in `step' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/rack-mini-profiler-2.3.1/lib/patches/net_patches.rb:18:in `request_with_mini_profiler' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/contrib/http/instrumentation.rb:42:in `request' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/rack-mini-profiler-2.3.1/lib/patches/net_patches.rb:19:in `block in request_with_mini_profiler' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/rack-mini-profiler-2.3.1/lib/mini_profiler/profiling_methods.rb:46:in `step' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/rack-mini-profiler-2.3.1/lib/patches/net_patches.rb:18:in `request_with_mini_profiler' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/contrib/http/instrumentation.rb:42:in `request' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/rack-mini-profiler-2.3.1/lib/patches/net_patches.rb:19:in `block in request_with_mini_profiler' 00:43
[root@stage.app.com] out: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/rack-mini-profiler-2.3.1/lib/mini_profiler/profiling_methods.rb:46:in `step'
...
```

using `gem "ddtrace"` on its own works fine though.

**Comment by marcotc** [comment]
Thank you for this bug report, @gingerlime. I'm taking a look soon.

For reference, what kind of application are you running in this case?

**Comment by marcotc** [comment]
👋 @gingerlime, I found documentation about stack level too deep errors from `rack-mini-profiler` itself: https://github.com/MiniProfiler/rack-mini-profiler#nethttp-stack-level-too-deep-errors

Would this address your issue? The problem is due to the use of `alias` in rack-mini-profiler, which gets changed by the suggested setting in docs.

Copying it here for visibility:

#### `Net::HTTP` stack level too deep errors

If you start seeing `SystemStackError: stack level too deep` errors from `Net::HTTP` after installing Mini Profiler, this means there is another patch for `Net::HTTP#request` that conflicts with Mini Profiler's patch in your application. To fix this, change `rack-mini-profiler` gem line in your `Gemfile` to the following:

```ruby
gem 'rack-mini-profiler', require: ['prepend_net_http_patch', 'rack-mini-profiler']
```

If you currently have `require: false`, remove the `'rack-mini-profiler'` string from the `require` array above so the gem line becomes like this:

```ruby
gem 'rack-mini-profiler', require: ['prepend_net_http_patch']
```

This conflict happens when a ruby method is patched twice, once using module prepend, and once using method aliasing. See this [ruby issue](https://bugs.ruby-lang.org/issues/11120) for details. The fix is to apply all patches the same way. Mini Profiler by default will apply its patch using method aliasing, but you can change that to module prepend by adding `require: ['prepend_net_http_patch']` to the gem line as shown above.

**Comment by gingerlime** [comment]
Hey @marcotc 👋 thank you! this seems to work around it. I'm wondering whether we actually need `auto_instrument` though, since now we have to put extra `require`s in our Gemfile, and it worked just fine beforehand... What's the benefit of `auto_instrument` over what we were using before?

**Comment by marcotc** [comment]
@gingerlime could you clarify what requires you are referring to here: "since now we have to put extra requires in our Gemfile"? Require for `ddtrace`, or for gems that you'd like to instrument?

I ask because gems that you'd like to instrument would already have to be required before.

Another question: are you running Rails or non-Rails? This is relevant because with Rails dependency requirement is preformed automatically in the correct order for `ddtrace`.

Also, if you had a working `Datadog.configure` block before, and you had settings configured (e.g. `service_name`) you won't get much value from migrating to `auto_instrument`. The only thing you'll get is that you won't need to add `c.use` if we introduce a new gem instrumentation in the future.

For new services, `auto_instrument` gives you a pretty good set of spans out of the box in your APM page.

**Comment by gingerlime** [comment]
> could you clarify what requires you are referring to here: "since now we have to put extra requires in our Gemfile"? Require for ddtrace, or for gems that you'd like to instrument?

I was referring to updating the `ddtrace` gem to add a require to auto instrument + specific requires for rack-mini-profiler to prepend the net http patch. 

> Another question: are you running Rails or non-Rails? This is relevant because with Rails dependency requirement is preformed automatically in the correct order for ddtrace.

Sorry, I missed this one. We're running a Rails app.

> Also, if you had a working Datadog.configure block before, and you had settings configured (e.g. service_name) you won't get much value from migrating to auto_instrument. The only thing you'll get is that you won't need to add c.use if we introduce a new gem instrumentation in the future.

Thank you. I guess we'll continue using `ddtrace` like we have done before and explicitly define any new instrumentation.

Thanks again for your help and patience, @marcotc. I think we can close this now :)
