### ISSUE TITLE
DEPRECATION WARNING: [] is deprecated and will be removed from Rails 6.2 (Use configs_for)

### ISSUE THREAD

**Issue by GeoffKarnov** [DataDog/dd-trace-rb#1349]
## Description

On application startup the following deprecation warning occurs:
```
ActiveSupport::DeprecationException:
  DEPRECATION WARNING: [] is deprecated and will be removed from Rails 6.2 (Use configs_for) (called from block in <top (required)> at my-app/config/initializers/datadog.rb:9)
# gem_path/ruby-2.7.2/gems/ddtrace-0.45.0/lib/ddtrace/vendor/active_record/connection_specification.rb:269:in `resolve_symbol_connection'
# gem_path/ruby-2.7.2/gems/ddtrace-0.45.0/lib/ddtrace/vendor/active_record/connection_specification.rb:253:in `resolve_connection'
# gem_path/ruby-2.7.2/gems/ddtrace-0.45.0/lib/ddtrace/vendor/active_record/connection_specification.rb:155:in `resolve'
# gem_path/ruby-2.7.2/gems/ddtrace-0.45.0/lib/ddtrace/contrib/active_record/configuration/resolver.rb:15:in `resolve'
# gem_path/ruby-2.7.2/gems/ddtrace-0.45.0/lib/ddtrace/contrib/configurable.rb:34:in `configuration_for?'
# gem_path/ruby-2.7.2/gems/ddtrace-0.45.0/lib/ddtrace/contrib/configurable.rb:49:in `configure'
# gem_path/ruby-2.7.2/gems/ddtrace-0.45.0/lib/ddtrace/contrib/extensions.rb:80:in `instrument'
# ./config/initializers/datadog.rb:9:in `block in <top (required)>'
```

The warning is triggered by this line extracted from my  `./config/initializers/datadog.rb`
```
  c.use :active_record, describes: :some_database, service_name: 'some-service-name'
```

## Versions

ddtrace (0.45.0)
rails 6.1.1

## Desired result

No deprecation warnings are emitted.

## Related information

Rails commit that adds the deprecation: https://github.com/rails/rails/commit/2a53fe638de2c485c2655b6b7236ec1ab7dca5ad

**Comment by marcotc** [comment]
Thank you very much, @GeoffKarnov! Seems like a straightforward fix in `ddtrace`, I'll get back to you when we release this fix.

**Comment by marcotc** [comment]
👋 @GeoffKarnov, version (0.46.0)[https://github.com/DataDog/dd-trace-rb/releases/tag/v0.46.0] has just been released, including the fix for the Rails' warnings.

**Comment by GeoffKarnov** [comment]
Awesome. Thanks. It all looks good. :+1:
