### ISSUE TITLE
Transport over unix socket on OS X

### ISSUE THREAD

**Issue by rodzyn** [DataDog/dd-trace-rb#1413]
I have a rails app running locally, with Datadog setup also locally (on host), everything works with default TCP/UDP communication (I see traces in the app).

I wanted to check unix socket integration. I turned it on in the global config (`datadog.yml`)
`dogstatsd_socket: "/var/run/datadog/dsd.socket"`

Changed tracer transport options accordingly:

```
            c.tracer.transport_options = proc { |t|
              t.adapter :unix, "/var/run/datadog/dsd.socket"
            }
```

What I am getting while running the app is:

` Internal error during HTTP transport request. Cause: Protocol wrong type for socket - connect(2)  for /var/run/datadog/dsd.socket `

Full errror:
```
D, [2021-03-17T17:58:30.648339 #3474] DEBUG -- ddtrace: [ddtrace] (/Users/marcin.olichwirowicz/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ddtrace-0.45.0/lib/ddtrace/transport/http/client.rb:33:in `rescue in send_request') Internal error during HTTP transport request. Cause: Protocol wrong type for socket - connect(2) for /var/run/datadog/dsd.socket Location: /Users/marcin.olichwirowicz/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ddtrace-0.45.0/lib/ddtrace/transport/http/adapters/unix_socket.rb:55:in `initialize'
```

Any advice?

Ruby version: 2.7.1, dd-trace 0.45.0

**Comment by rodzyn** [comment]
Ok, I found a setting:

`receiver_socket` in `datadog.yml`, it turns out it needs to be set as well to work properly in this setup.
