### ISSUE TITLE
ddtrace client error "Internal error during HTTP transport request"

### ISSUE THREAD

**Issue by jshah** [DataDog/dd-trace-rb#1446]
## Problem

I have implemented `dd-trace` already for one environment which is working great and I am seeing APMs in Datadog. However, when I tried to implement `dd-trace` for our staging environment (more traffic on this one), I get an "Internal error during HTTP transport request".

I'm having a similar issue as https://github.com/DataDog/dd-trace-rb/issues/1085 though my error is not during `http/net` but rather in `socksify`:

## Error Logs
```
E, [2021-03-31T21:41:42.553406 #14] ERROR -- ddtrace: [ddtrace] (/app/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/transport/http/client.rb:35:in `rescue in send_request') Internal error during HTTP transport request. Cause: execution expired Location: /app/vendor/bundle/ruby/2.6.0/gems/socksify-1.7.1/lib/socksify.rb:178:in `initialize'
--
```

Followed by:
```
I, [2021-04-01T18:41:33.588756 #13]  INFO -- ddtrace: [ddtrace] DATADOG TRACER CONFIGURATION - 
{
    "date": "2021-04-01T18:41:33+00:00",
    "os_name": "x86_64-pc-linux-gnu",
    "version": "0.45.0",
    "lang": "ruby",
    "lang_version": "2.6.6",
    "env": "staging",
    "enabled": true,
    "service": "dg_app",
    "agent_url": "http://<hidden_ip>:8126?timeout=1",
    "agent_error": "Datadog::Transport::InternalErrorResponse ok?: unsupported?:, not_found?:, client_error?:, server_error?:, internal_error?:true, payload:, error_type:Net::OpenTimeout error:execution expired",
    "debug": false,
    "analytics_enabled": false,
    "tags": "env:staging",
    "runtime_metrics_enabled": false,
    "integrations_loaded": "aws@3.90.1,delayed_job@4.1.5,rails@5.2.4.5,redis@4.0.3,sidekiq@5.2.2,rack@2.2.3,action_cable@5.2.4.5,active_support@5.2.4.5,action_pack@5.2.4.5,action_view@5.2.4.5,active_record@5.2.4.5",
    "vm": "ruby-2.6.6",
    "partial_flushing_enabled": false,
    "priority_sampling_enabled": false,
    "health_metrics_enabled": false,
    "integration_aws_analytics_enabled": "false",
    "integration_aws_analytics_sample_rate": "1.0",
    "integration_aws_enabled": "true",
    "integration_aws_service_name": "aws",
    "integration_delayed_job_analytics_enabled": "false",
    "integration_delayed_job_analytics_sample_rate": "1.0",
    "integration_delayed_job_enabled": "true",
    "integration_delayed_job_service_name": "delayed_job",
    "integration_delayed_job_client_service_name": "delayed_job-client",
    "integration_delayed_job_error_handler": "#<Proc:0x00005557da4a44d0@/app/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/tracer.rb:28>",
    "integration_rails_analytics_enabled": "",
    "integration_rails_analytics_sample_rate": "1.0",
    "integration_rails_enabled": "true",
    "integration_rails_service_name": "dg_app",
    "integration_rails_cache_service": "dg_app-cache",
    "integration_rails_controller_service": "dg_app",
    "integration_rails_database_service": "dg_app-postgres",
    "integration_rails_distributed_tracing": "true",
    "integration_rails_exception_controller": "",
    "integration_rails_middleware": "true",
    "integration_rails_middleware_names": "false",
    "integration_rails_template_base_path": "views/",
    "integration_rails_log_injection": "false",
    "integration_redis_analytics_enabled": "false",
    "integration_redis_analytics_sample_rate": "1.0",
    "integration_redis_enabled": "true",
    "integration_redis_service_name": "redis",
    "integration_redis_command_args": "true",
    "integration_sidekiq_analytics_enabled": "false",
    "integration_sidekiq_analytics_sample_rate": "1.0",
    "integration_sidekiq_enabled": "true",
    "integration_sidekiq_service_name": "sidekiq",
    "integration_sidekiq_tag_args": "false",
    "integration_sidekiq_client_service_name": "sidekiq-client",
    "integration_sidekiq_error_handler": "#<Proc:0x00005557da4a44d0@/app/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/tracer.rb:28>",
    "integration_rack_analytics_enabled": "",
    "integration_rack_analytics_sample_rate": "1.0",
    "integration_rack_enabled": "true",
    "integration_rack_service_name": "dg_app",
    "integration_rack_application": "#<DGApp::Application:0x00005557df5fc878>",
    "integration_rack_distributed_tracing": "true",
    "integration_rack_headers": "{:response=>[\"Content-Type\", \"X-Request-ID\"]}",
    "integration_rack_middleware_names": "false",
    "integration_rack_quantize": "{}",
    "integration_rack_request_queuing": "false",
    "integration_rack_web_service_name": "web-server",
    "integration_action_cable_analytics_enabled": "false",
    "integration_action_cable_analytics_sample_rate": "1.0",
    "integration_action_cable_enabled": "true",
    "integration_action_cable_service_name": "dg_app-action_cable",
    "integration_active_support_analytics_enabled": "false",
    "integration_active_support_analytics_sample_rate": "1.0",
    "integration_active_support_enabled": "true",
    "integration_active_support_service_name": "",
    "integration_active_support_cache_service": "dg_app-cache",
    "integration_action_pack_analytics_enabled": "",
    "integration_action_pack_analytics_sample_rate": "1.0",
    "integration_action_pack_enabled": "true",
    "integration_action_pack_service_name": "dg_app",
    "integration_action_pack_controller_service": "dg_app",
    "integration_action_pack_exception_controller": "",
    "integration_action_view_analytics_enabled": "false",
    "integration_action_view_analytics_sample_rate": "1.0",
    "integration_action_view_enabled": "true",
    "integration_action_view_service_name": "dg_app",
    "integration_action_view_template_base_path": "views/",
    "integration_active_record_analytics_enabled": "false",
    "integration_active_record_analytics_sample_rate": "1.0",
    "integration_active_record_enabled": "true",
    "integration_active_record_service_name": "dg_app-postgres",
    "integration_active_record_orm_service_name": ""
}
```

```
W, [2021-03-31T21:41:42.556798 #14]  WARN -- ddtrace: [ddtrace] DATADOG TRACER DIAGNOSTIC - Agent Error: Datadog::Transport::InternalErrorResponse ok?: unsupported?:, not_found?:, client_error?:, server_error?:, internal_error?:true, payload:, error_type:Net::OpenTimeout error:execution expired
--
```

## Memory/CPU
Our Memory/CPU utilization looks fine as well though, thing to note is that the error happens right on startup so our app never even connects to the client.
![CleanShot 2021-04-01 at 11 19 24](https://user-images.githubusercontent.com/1421038/113337188-49969d80-92dc-11eb-8ea6-76750daeff99.png)

## Possible Solution
I also saw this comment (https://github.com/DataDog/dd-trace-rb/issues/1085#issuecomment-741174391) and before I attempt to do this, I wanted to reach out and verify this is the recommended solution.

Please let me know if you need any other information!

**Comment by delner** [comment]
@jshah Thanks for the report and the diagnostics! `Cause: execution expired` stems from Ruby's `Timeout` code; I believe the `Net:HTTP` module is using this and `socksify` likely modifies that library hence why it appears in the stack trace.

The core of the issue is why the timeout occurred; if it's a temporary network issue, trouble opening a socket etc... it's difficult to pinpoint what caused the timeout as the environment is a big factor. But it might be possible to avoid it by extending the default timeout beyond our current 1 second interval (which may be too tight.) It's worth trying https://github.com/DataDog/dd-trace-rb/issues/1085#issuecomment-741174391 to see if it prevents this error. Let me know how that works!

**Comment by jshah** [comment]
Hi @delner, I tried updating my datadog configuration to increase the timeout but now I'm getting an error to connect to the client. I believe it's due to the `net_http` adapter setting the hostname to localhost (`'127.0.0.1'`) regardless of what we pass into the adapter.

We are running on ECS so we have logic to check for the datadog-agent depending on whether we're running on an EC2 instance or on Fargate. Our dd-trace client runs fine for Fargate since there is an agent available on localhost but fails on EC2.

```ruby
if ENV['ENABLE_DATADOG'] && Rails.env.production? && !defined?(Rails::Console)
    require 'ddtrace/auto_instrument'

    hostname =
      case ENV['AWS_EXECUTION_ENV']
      when 'AWS_ECS_EC2'
        # EC2 services have a daemon on each instance
        # This will get the IP for the EC2 instance we are running on
        open('http://169.254.169.254/latest/meta-data/local-ipv4', { read_timeout: 3, open_timeout: 3 }).read
      when 'AWS_ECS_FARGATE'
        # Fargate services have a local datadog-agent as part of their task definitions
        '127.0.0.1'
      end
    Datadog.configure do |c|
      c.tracer.enabled = true
      c.tracer hostname: hostname
      c.tracer.transport_options = proc { |t|
        t.adapter :net_http,
                  hostname,
                  Datadog::Transport::HTTP.default_port,
                  { timeout: 30 }
      }

      c.service = ENV['SERVICE_NAME'] if ENV['SERVICE_NAME'].present?
    end
  end
```

I see the following error:

```
E, [2021-04-08T18:39:37.338500 #1] ERROR -- ddtrace: [ddtrace] (/app/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/transport/http/client.rb:35:in `rescue in send_request') Internal error during HTTP transport request. Cause: Failed to open TCP connection to 127.0.0.1:8126 (Connection refused - connect(2) for "127.0.0.1" port 8126) Location: /usr/local/lib/ruby/2.6.0/net/http.rb:949:in `rescue in block in connect'
--
```

I would expect me setting hostname on the `net_http` adapter would overwrite the `default_hostname`

**Comment by jshah** [comment]
Also pinging @marcotc since the timeout fix was recommended by you

**Comment by delner** [comment]
@jshah Are you sure your case statement is working as expected? Using the latest `ddtrace`, I added the following configuration:

```ruby
hostname = 'foobar'
c.tracer hostname: hostname
c.tracer.transport_options = proc do |t|
  t.adapter :net_http,
            hostname,
            Datadog::Transport::HTTP.default_port,
            { timeout: 30 }
end
```

And added the following after `Datadog.configure`:

```ruby
puts "Datadog configured!"
transport = Datadog.tracer.writer.transport
adapter = transport.apis[transport.current_api_id].adapter
puts "Destination: #{adapter.hostname}:#{adapter.port}"
puts "Timeout: #{adapter.timeout}"
```

Which when started in Puma, produced:

```
Datadog configured!
Destination: foobar:8126
Timeout: 30
```

So I think swapping the adapter hostname works fine, there just might be some other factor that's causing your outcome.

**Comment by jshah** [comment]
@delner yes, I've verified that my case statement is returning a string IP. It returns `'127.0.0.1'` for Fargate and a string EC2 instance IP when running on EC2.

```
# running in our staging environment

[staging]> hostname = case ENV['AWS_EXECUTION_ENV']
[staging]* when 'AWS_ECS_EC2'
[staging]*   open('http://169.254.169.254/latest/meta-data/local-ipv4', { read_timeout: 3, open_timeout: 3 }).read
[staging]* when 'AWS_ECS_FARGATE'
[staging]*   '127.0.0.1'
[staging]* end
=> "10.x.x.x"
```

When I replicate your exact commands locally, I get similar outputs as yours:

```
require 'ddtrace/auto_instrument'

hostname = case ENV['AWS_EXECUTION_ENV']
           when 'AWS_ECS_EC2'
             # EC2 services have a daemon on each instance
             # This will get the IP for the EC2 instance we are running on
             open('http://169.254.169.254/latest/meta-data/local-ipv4', { read_timeout: 3, open_timeout: 3 }).read
           when 'AWS_ECS_FARGATE'
             # Fargate services have a local datadog-agent as part of their task definitions
             '127.0.0.1'
		   else
			 'test'
           end
Rails.logger.info("Setting Datadog hostname: #{hostname}")

Datadog.configure do |c|
  c.tracer.enabled = true
  c.tracer hostname: hostname
  c.tracer.transport_options = proc do |t|
    t.adapter :net_http, hostname, Datadog::Transport::HTTP.default_port, { timeout: 30 }
  end

  c.env = ENV['DG_REALM'] if ENV['DG_REALM'].present?
  c.service = ENV['SERVICE_NAME'] if ENV['SERVICE_NAME'].present?
end

Rails.logger.info('Datadog configured!')
transport = Datadog.tracer.writer.transport
adapter = transport.apis[transport.current_api_id].adapter
Rails.logger.info("Destination: #{adapter.hostname}:#{adapter.port}")
Rails.logger.info("Timeout: #{adapter.timeout}")
```

which results in

```
Setting Datadog hostname: test
Datadog configured!
Destination: test:8126
Timeout: 30
```

In my staging environment, I see something similar but I also see an error output before:

```
E, [2021-04-09T18:56:23.426393 #1] ERROR -- ddtrace: [ddtrace] (/app/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/transport/http/client.rb:35:in `rescue in send_request') Internal error during HTTP transport request. Cause: Failed to open TCP connection to 127.0.0.1:8126 (Connection refused - connect(2) for "127.0.0.1" port 8126) Location: /usr/local/lib/ruby/2.6.0/net/http.rb:949:in `rescue in block in connect'
--
```

followed by

```
Setting Datadog hostname: 10.x.x.x
Datadog configured!
Destination: 10.x.x.x:8126
Timeout: 30
```

I can confirm that the hostname and timeout is being set correctly. Could it be something with `auto_instrument` overriding default values and then bombing out the rest of the traces?

**Comment by jshah** [comment]
Hi @delner, any update on this? This is currently blocking us from getting APM implemented. Please let me know if I can help with any further information.

**Comment by delner** [comment]
The following code should reflect what's actually in use:

```
transport = Datadog.tracer.writer.transport
adapter = transport.apis[transport.current_api_id].adapter
puts "Destination: #{adapter.hostname}:#{adapter.port}"
```

So it's interesting that you see `"agent_url": "http://127.0.0.1:8126?timeout=1"` in your tracer configuration. That shouldn't be the case so we'll see if we can replicate on our end.

**Comment by jshah** [comment]
Hi @delner, 

I tried removing `auto_instrument` and explicitly using the integrations which resulted in the correct hostname and timeout being picked up in the Tracer Configuration but still erroring out on `socksify`.

`socksify` no longer fails on trying to connect to `127.0.0.1` but again on the initial error of `Internal error during HTTP transport request. Cause: execution expired Location`. See below:

```
E, [2021-04-14T21:10:02.518491 #23] ERROR -- ddtrace: [ddtrace] (/app/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/transport/http/client.rb:35:in `rescue in send_request') Internal error during HTTP transport request. Cause: execution expired Location: /app/vendor/bundle/ruby/2.6.0/gems/socksify-1.7.1/lib/socksify.rb:178:in `initialize'
--
```

Tracer Configuration:

```
I, [2021-04-14T21:10:02.522421 #23]  INFO -- ddtrace: [ddtrace] DATADOG TRACER CONFIGURATION - 
{
    "date": "2021-04-14T21:10:02+00:00",
    "os_name": "x86_64-pc-linux-gnu",
    "version": "0.45.0",
    "lang": "ruby",
    "lang_version": "2.6.6",
    "env": "staging",
    "enabled": true,
    "service": "dg_app",
    "agent_url": "http://10.x.x.x:8126?timeout=30",
    "agent_error": "Datadog::Transport::InternalErrorResponse ok?: unsupported?:, not_found?:, client_error?:, server_error?:, internal_error?:true, payload:, error_type:Net::OpenTimeout error:execution expired",
    "debug": false,
    "analytics_enabled": false,
    "tags": "env:staging",
    "runtime_metrics_enabled": false,
    "integrations_loaded": "aws@3.90.1,delayed_job@4.1.5,faraday@0.15.4,httpclient@2.8.3,rails@5.2.4.5,rake@12.3.3,redis@4.0.3,rest_client@2.0.2,sidekiq@5.2.2,rack@2.2.3,action_cable@5.2.4.5,active_support@5.2.4.5,action_pack@5.2.4.5,action_view@5.2.4.5,active_record@5.2.4.5",
    "vm": "ruby-2.6.6",
    "partial_flushing_enabled": false,
    "priority_sampling_enabled": false,
    "health_metrics_enabled": false,
    "integration_aws_analytics_enabled": "false",
    "integration_aws_analytics_sample_rate": "1.0",
    "integration_aws_enabled": "true",
    "integration_aws_service_name": "aws",
    "integration_delayed_job_analytics_enabled": "false",
    "integration_delayed_job_analytics_sample_rate": "1.0",
    "integration_delayed_job_enabled": "true",
    "integration_delayed_job_service_name": "delayed_job",
    "integration_delayed_job_client_service_name": "delayed_job-client",
    "integration_delayed_job_error_handler": "#<Proc:0x0000563979197f18@/app/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/tracer.rb:28>",
    "integration_faraday_analytics_enabled": "false",
    "integration_faraday_analytics_sample_rate": "1.0",
    "integration_faraday_enabled": "true",
    "integration_faraday_service_name": "faraday",
    "integration_faraday_distributed_tracing": "true",
    "integration_faraday_error_handler": "#<Proc:0x000056397c5da668@/app/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/contrib/faraday/configuration/settings.rb:11 (lambda)>",
    "integration_faraday_split_by_domain": "false",
    "integration_httpclient_analytics_enabled": "false",
    "integration_httpclient_analytics_sample_rate": "1.0",
    "integration_httpclient_enabled": "true",
    "integration_httpclient_service_name": "httpclient",
    "integration_httpclient_distributed_tracing": "true",
    "integration_httpclient_split_by_domain": "false",
    "integration_rails_analytics_enabled": "",
    "integration_rails_analytics_sample_rate": "1.0",
    "integration_rails_enabled": "true",
    "integration_rails_service_name": "dg_app",
    "integration_rails_cache_service": "dg_app-cache",
    "integration_rails_controller_service": "dg_app",
    "integration_rails_database_service": "dg_app-postgres",
    "integration_rails_distributed_tracing": "true",
    "integration_rails_exception_controller": "",
    "integration_rails_middleware": "true",
    "integration_rails_middleware_names": "false",
    "integration_rails_template_base_path": "views/",
    "integration_rails_log_injection": "false",
    "integration_rake_analytics_enabled": "false",
    "integration_rake_analytics_sample_rate": "1.0",
    "integration_rake_enabled": "true",
    "integration_rake_service_name": "rake",
    "integration_rake_quantize": "{}",
    "integration_redis_analytics_enabled": "false",
    "integration_redis_analytics_sample_rate": "1.0",
    "integration_redis_enabled": "true",
    "integration_redis_service_name": "redis",
    "integration_redis_command_args": "true",
    "integration_rest_client_analytics_enabled": "false",
    "integration_rest_client_analytics_sample_rate": "1.0",
    "integration_rest_client_enabled": "true",
    "integration_rest_client_service_name": "rest_client",
    "integration_rest_client_distributed_tracing": "true",
    "integration_sidekiq_analytics_enabled": "false",
    "integration_sidekiq_analytics_sample_rate": "1.0",
    "integration_sidekiq_enabled": "true",
    "integration_sidekiq_service_name": "sidekiq",
    "integration_sidekiq_tag_args": "false",
    "integration_sidekiq_client_service_name": "sidekiq-client",
    "integration_sidekiq_error_handler": "#<Proc:0x0000563979197f18@/app/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.45.0/lib/ddtrace/tracer.rb:28>",
    "integration_rack_analytics_enabled": "",
    "integration_rack_analytics_sample_rate": "1.0",
    "integration_rack_enabled": "true",
    "integration_rack_service_name": "dg_app",
    "integration_rack_application": "#<DGApp::Application:0x0000563980c0e7b0>",
    "integration_rack_distributed_tracing": "true",
    "integration_rack_headers": "{:response=>[\"Content-Type\", \"X-Request-ID\"]}",
    "integration_rack_middleware_names": "false",
    "integration_rack_quantize": "{}",
    "integration_rack_request_queuing": "false",
    "integration_rack_web_service_name": "web-server",
    "integration_action_cable_analytics_enabled": "false",
    "integration_action_cable_analytics_sample_rate": "1.0",
    "integration_action_cable_enabled": "true",
    "integration_action_cable_service_name": "dg_app-action_cable",
    "integration_active_support_analytics_enabled": "false",
    "integration_active_support_analytics_sample_rate": "1.0",
    "integration_active_support_enabled": "true",
    "integration_active_support_service_name": "",
    "integration_active_support_cache_service": "dg_app-cache",
    "integration_action_pack_analytics_enabled": "",
    "integration_action_pack_analytics_sample_rate": "1.0",
    "integration_action_pack_enabled": "true",
    "integration_action_pack_service_name": "dg_app",
    "integration_action_pack_controller_service": "dg_app",
    "integration_action_pack_exception_controller": "",
    "integration_action_view_analytics_enabled": "false",
    "integration_action_view_analytics_sample_rate": "1.0",
    "integration_action_view_enabled": "true",
    "integration_action_view_service_name": "dg_app",
    "integration_action_view_template_base_path": "views/",
    "integration_active_record_analytics_enabled": "false",
    "integration_active_record_analytics_sample_rate": "1.0",
    "integration_active_record_enabled": "true",
    "integration_active_record_service_name": "dg_app-postgres",
    "integration_active_record_orm_service_name": ""
}
```

It seems like increasing the timeout isn't the issue here? Let me know if you need anything else.

**Comment by delner** [comment]
@jshah Does this error still occur without `socksify`? Can you disable it and see if it works?

If it's producing an error on `127.0.0.1` that's expected, but if it has an error when pointed at the correct host with a timeout of at least 5 seconds, then there's no point upping to 30 or beyond; there's clearly some network connectivity issue.

Our goal here is to see if 1) Datadog is at all misconfiguring the hostname (something I'm so far unable to replicate), or 2) if `socksify` or other library is breaking Datadog (in which case we'd want to figure out if that library has the bug or we do.) If neither of these scenarios are the case, then I'm not sure how much more we can do from this end, as it would appear to be network connectivity issues.

**Comment by jshah** [comment]
@delner `socksify` is a dependency for us so we can't disable it but let me see if I can work around it.

The odd part is that we have tracing working for one of our environments already, but it bombs out for the current one that's showing these errors (higher traffic/volume on this environment). The setup is exactly the same as the environment where we have tracing working.

Are there are any test connection methods we can try running directly through curl or through the rails console to test network connectivity? I've tried simply curling the `host:port` from the application container and got:

```
root@ip-10-x-x-x:/app# curl 10.x.x.x:8126
404 page not found
```

**Comment by jshah** [comment]
@delner I've found the issue. Thank you for looking into it, sorry for the trouble!

I was double-checking our AWS security groups for the environment where the issues were happening. I noticed we didn't have port `8126` as an inbound rule but we did for the environment where the APM was working. 

For AWS ECS, you have to self-reference your security groups on the `datadog-agent` port to allow requests to go through (https://stackoverflow.com/a/51568967/1258421). Hope this helps someone in the future...
