### ISSUE TITLE
Failed to apply Datadog::Contrib::Rails::Patcher patch. Cause: can't modify frozen Array

### ISSUE THREAD

**Issue by olkeene** [DataDog/dd-trace-rb#1468]
Hi guys.
I'm getting the below error on `v0.47` and the latest master `ab0a4e07f888` on attempt to insert `Datadog::Contrib::Rack::TraceMiddleware`
https://github.com/DataDog/dd-trace-rb/blob/ab0a4e07f888f3e231f57de80f1132879cbc9906/lib/ddtrace/contrib/rails/patcher.rb#L45-L47

```
RAILS_VERSION = '6.1.3.1'
gem 'railties', RAILS_VERSION
gem 'activesupport', RAILS_VERSION
gem 'activemodel', RAILS_VERSION
gem 'actionpack', RAILS_VERSION
gem 'actionmailer', RAILS_VERSION
gem 'actionview', RAILS_VERSION
```

```
ERROR -- ddtrace: [ddtrace] (/bundle/ruby/2.6.0/bundler/gems/dd-trace-rb-ab0a4e07f888/lib/ddtrace/contrib/patcher.rb:41:in `on_patch_error') 
Failed to apply Datadog::Contrib::Rails::Patcher patch. Cause: can't modify frozen Array Location: /bundle/ruby/2.6.0/gems/actionpack-6.1.3.1/lib/action_dispatch/middleware/stack.rb:102:in `insert'
```

Appreciated in advance

**Comment by marcotc** [comment]
👋 @olkeene, thanks for reporting this issue.

It seems like the Datadog gem is trying to instrument Rails after it's been initialized.

I've tried create a Rails 6.1.3.1 application, using Ruby 3.0, and instrumenting it by adding `gem 'ddtrace', require: 'ddtrace/auto_instrument'` to the Gemfile. Using `ddtrace` version `0.47.0`.

Running this app with `DD_TRACE_DEBUG=true bin/rails s` (`DD_TRACE_DEBUG=true` enables verbose `ddtrace` logging), and got the desired output of 7 spans inside a larger trace when hitting the Rails welcome page:

```
[2021-04-19T14:24:30] DEBUG -- ddtrace: [ddtrace] (ddtrace-0.47.0/lib/ddtrace/tracer.rb:362:in `write') Writing 7 spans (enabled: true)
[2021-04-19T14:24:30] DEBUG -- ddtrace: [ddtrace] (ddtrace-0.47.0/lib/ddtrace/tracer.rb:365:in `write') [
 Name: rack.request
Span ID: 1813539796257433374
Parent ID: 0
Trace ID: 3950274138443676317
Type: web
Service: test_app
Resource: Rails::WelcomeController#index
Error: 0
Start: 1618867470631574016
End: 1618867470773925120
Duration: 0.1423479998484254
Allocations: 48165
Tags: [
   runtime-id => f05f925c-604d-4486-8523-3700db2da92c,
   http.method => GET,
   http.url => /,
   http.base_url => http://127.0.0.1:3000,
   http.status_code => 200,
   http.response.headers.content_type => text/html; charset=utf-8,
   http.response.headers.x_request_id => 3de3147b-9943-48b0-b234-e96310bff987]
Metrics: [
   _dd.agent_psr => 1.0,
   system.pid => 46852.0,
   _dd.measured => 1.0,
   _sampling_priority_v1 => 1.0],

 Name: sqlite.query
Span ID: 3246109941455564622
Parent ID: 1813539796257433374
Trace ID: 3950274138443676317
Type: sql
Service: test_app-sqlite
Resource: PRAGMA foreign_keys = ON
Error: 0
Start: 1618867470711444992
End: 1618867470713024000
Duration: 0.0015809996984899044
Allocations: 340
Tags: [
   peer.service => test_app-sqlite,
   active_record.db.vendor => sqlite,
   active_record.db.name => /private/tmp/test-app/db/development.sqlite3]
Metrics: [
   ],

 Name: sqlite.query
Span ID: 2110332737751785293
Parent ID: 1813539796257433374
Trace ID: 3950274138443676317
Type: sql
Service: test_app-sqlite
Resource: SELECT sqlite_version(*)
Error: 0
Start: 1618867470713153024
End: 1618867470715644928
Duration: 0.0024939998984336853
Allocations: 894
Tags: [
   peer.service => test_app-sqlite,
   active_record.db.vendor => sqlite,
   active_record.db.name => /private/tmp/test-app/db/development.sqlite3]
Metrics: [
   ],

 Name: sqlite.query
Span ID: 838270216449707780
Parent ID: 1813539796257433374
Trace ID: 3950274138443676317
Type: sql
Service: test_app-sqlite
Resource: SELECT name FROM sqlite_master WHERE name <> 'sqlite_sequence' AND type IN ('table','view')
Error: 0
Start: 1618867470733671936
End: 1618867470734042112
Duration: 0.0003659999929368496
Allocations: 37
Tags: [
   peer.service => test_app-sqlite,
   active_record.db.vendor => sqlite,
   active_record.db.name => /private/tmp/test-app/db/development.sqlite3]
Metrics: [
   ],

 Name: sqlite.query
Span ID: 4331047619711417071
Parent ID: 1813539796257433374
Trace ID: 3950274138443676317
Type: sql
Service: test_app-sqlite
Resource: SELECT name FROM sqlite_master WHERE name <> 'sqlite_sequence' AND name = 'schema_migrations' AND type IN ('table','view')
Error: 0
Start: 1618867470734147072
End: 1618867470734284032
Duration: 0.00013800011947751045
Allocations: 37
Tags: [
   peer.service => test_app-sqlite,
   active_record.db.vendor => sqlite,
   active_record.db.name => /private/tmp/test-app/db/development.sqlite3]
Metrics: [
   ],

 Name: rails.action_controller
Span ID: 3994237674218639460
Parent ID: 1813539796257433374
Trace ID: 3950274138443676317
Type: web
Service: test_app
Resource: Rails::WelcomeController#index
Error: 0
Start: 1618867470755585024
End: 1618867470768665088
Duration: 0.013078000396490097
Allocations: 1941
Tags: [
   rails.route.action => index,
   rails.route.controller => Rails::WelcomeController]
Metrics: [
   _dd.measured => 1.0],

 Name: rails.render_template
Span ID: 2271777381740288831
Parent ID: 3994237674218639460
Trace ID: 3950274138443676317
Type: template
Service: test_app
Resource: index.html.erb
Error: 0
Start: 1618867470760665088
End: 1618867470768069120
Duration: 0.007406999822705984
Allocations: 481
Tags: [
   rails.template_name => index.html.erb]
Metrics: [ _dd.measured => 1.0]]
```

Could you share with us how you are instrumenting your application with `ddtrace`?
This could be the `ddtrace` line in your Gemfile, or any calls to `/Datadog\..*/` in your application.

**Comment by olkeene** [comment]
@marcotc thanks for the reply.
Seems, I've found the issue:
```
require 'ddtrace'
instead of 
require 'ddtrace/auto_instrument'
```

After requiring the proper file I don't see any error
