### ISSUE TITLE
Error while parsing container info undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by gingerlime** [DataDog/dd-trace-rb#1496]
Just noticed this error after running `RAILS_ENV=production bundle exec rake db:migrate`

Rails: 6.0.3.7
ddtrace: 0.48.0
ruby: 2.6.5

```
RAILS_ENV=production bundle exec rake db:migrate

E, [2021-05-06T07:04:59.125373 #28553] ERROR -- ddtrace: [ddtrace] (/var/local/app/new/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.48.0/lib/ddtrace/runtime/container.rb:71:in `rescue in block in descriptor') Error while parsing container info. Cause: undefined method `[]' for nil:NilClass Location: /var/local/app/new/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.48.0/lib/ddtrace/runtime/container.rb:57:in `block (2 levels) in descriptor'

I, [2021-05-06T07:04:59.305723 #28553]  INFO -- ddtrace: [ddtrace] DATADOG TRACER CONFIGURATION - {"date":"2021-05-06T07:04:59+00:00","os_name":"x86_64-pc-linux-gnu","version":"0.48.0","lang":"ruby","lang_version":"2.6.5","env":"production","enabled":true,"agent_url":"http://127.0.0.1:8127?timeout=1","debug":false,"analytics_enabled":false,"tags":"env:production","runtime_metrics_enabled":false,"integrations_loaded":"rails@6.0.3.7,redis@4.2.5,sidekiq@6.2.1,http@2.6.5","vm":"ruby-2.6.5","partial_flushing_enabled":false,"priority_sampling_enabled":false,"health_metrics_enabled":false,"integration_rails_analytics_enabled":"","integration_rails_analytics_sample_rate":"1.0","integration_rails_enabled":"true","integration_rails_service_name":"app","integration_rails_cache_service":"rails-cache","integration_rails_controller_service":"rails-controller","integration_rails_database_service":"","integration_rails_distributed_tracing":"true","integration_rails_exception_controller":"","integration_rails_middleware":"true","integration_rails_middleware_names":"false","integration_rails_template_base_path":"views/","integration_rails_log_injection":"false","integration_redis_analytics_enabled":"false","integration_redis_analytics_sample_rate":"1.0","integration_redis_enabled":"true","integration_redis_service_name":"redis","integration_redis_command_args":"true","integration_sidekiq_analytics_enabled":"false","integration_sidekiq_analytics_sample_rate":"1.0","integration_sidekiq_enabled":"true","integration_sidekiq_service_name":"sidekiq","integration_sidekiq_tag_args":"false","integration_sidekiq_client_service_name":"sidekiq-client","integration_sidekiq_error_handler":"#\u003cProc:0x000055c1701e00c8@/var/local/app/new/vendor/bundle/ruby/2.6.0/gems/ddtrace-0.48.0/lib/ddtrace/tracer.rb:32\u003e","integration_http_analytics_enabled":"false","integration_http_analytics_sample_rate":"1.0","integration_http_enabled":"true","integration_http_service_name":"net/http","integration_http_distributed_tracing":"true","integration_http_split_by_domain":"false"}
```

**Comment by marcotc** [comment]
Hi @gingerlime, thank you for the issue report.
I think this is the same issue as https://github.com/DataDog/dd-trace-rb/issues/1475, which we addressed in https://github.com/DataDog/dd-trace-rb/pull/1487.

We'll have an official release with that fix soon, but in the meantime, you could use the prerelease gem built on top of https://github.com/DataDog/dd-trace-rb/pull/1487:
```ruby
source 'http://gems.datadoghq.com/prerelease' do
  gem 'ddtrace', '0.48.0.fix.container.parsing.k8s.cgroups.132229'
end
```

**Comment by gingerlime** [comment]
Sorry I missed #1475. Good to know it's fixed and hope it gets released soon. Other than the error, there are no side effects I could spot, so we're happy to wait. I'll close this one then. Thanks for your help @marcotc

**Comment by ericmustin** [comment]
👋  Hi @gingerlime , hope all is well, v0.49.0 is released if you'd like to upgrade and see if this resolves the issue. Cheers! https://github.com/DataDog/dd-trace-rb/releases/tag/v0.49.0

**Comment by gingerlime** [comment]
Hey @ericmustin yeah, seems to work now! :) thank you 👍
