### ISSUE TITLE
v0.49 Failed to apply Datadog::Contrib::Rails::Patcher patch. Cause: can't modify frozen Array

### ISSUE THREAD

**Issue by olkeene** [DataDog/dd-trace-rb#1519]
Hi guys.
After upgrade to `v0.49`, we're getting the next error. Was verified on master as well.
`DD_TRACE_DEBUG=true` doesn't enable verbose logging as was in `v0.47`

Gemfile
```
gem 'ddtrace', '0.49.0', require: false
```

initializers/datadog.rb
```
if Rails.configuration.datadog_enabled.to_s == 'true'
  require 'ddtrace/auto_instrument'

  Rails.application.config.after_initialize do
    # https://docs.datadoghq.com/tracing/setup_overview/setup/ruby/
    # https://docs.datadoghq.com/agent/docker/apm/?tab=linux
    # DATADOG_ENABLED=true
    # DD_APM_ENABLED=true
    # DD_API_KEY=X
    Datadog.configure do |config|
      config.service = Sidekiq.server? ? 'sidekiq' : 'api'
      config.env = Rails.env
      config.version = ENV['HEROKU_RELEASE_VERSION']
      config.tracer(enabled: false) if Rails.env.test? || Rails.env.development?

      # This will activate auto-instrumentation for Rails
      config.with_options(analytics_enabled: true) do |c|
        c.use(:rack)
        c.use(:rails)
        c.use(:sidekiq)

        c.use(:action_view)
        c.use(:action_pack)
        c.use(:active_support)

        c.use(:elasticsearch)
        c.use(:graphql, schemas: [RxVantageSchema])
        c.use(:mysql2)
        c.use(:sequel)
        c.use(:http)
        c.use(:redis)
      end
    end
  end
end
```

Output
```
DATADOG_ENABLED=true DD_TRACE_DEBUG=true bundle exec rails s

=> Booting Puma
=> Rails 6.1.3.1 application starting in development 
=> Run `bin/rails server --help` for more startup options
D, [2021-05-26T02:01:05.767434 #1635] DEBUG -- ddtrace: [ddtrace] (/bundle/ruby/2.6.0/gems/ddtrace-0.49.0/lib/ddtrace/configuration/components.rb:181:in `startup!') Profiling is disabled
E, [2021-05-26T02:01:05.768156 #1635] ERROR -- ddtrace: [ddtrace] (/bundle/ruby/2.6.0/gems/ddtrace-0.49.0/lib/ddtrace/contrib/patcher.rb:41:in `on_patch_error') Failed to apply Datadog::Contrib::Rails::Patcher patch. Cause: can't modify frozen Array Location: /bundle/ruby/2.6.0/gems/actionpack-6.1.3.1/lib/action_dispatch/middleware/stack.rb:102:in `insert'
Puma starting in single mode...
* Version 4.3.7 (ruby 2.6.6-p146), codename: Mysterious Traveller
* Min threads: 1, max threads: 16
* Environment: development
* Listening on tcp://127.0.0.1:3000
Use Ctrl-C to stop
```

Appreciated in advance

**Comment by ericmustin** [comment]
we don't recommend configuration in this block ` Rails.application.config.after_initialize`

per our documentation, we suggest you use an initializers file:

https://docs.datadoghq.com/tracing/setup_overview/setup/ruby/#quickstart-for-rails-applications

```
Create a config/initializers/datadog.rb file containing:

Datadog.configure do |c|
  # This will activate auto-instrumentation for Rails
  c.use :rails
end
```

Can you try using the documented setup path and seeing if that resolves your issue?

**Comment by ericmustin** [comment]
just circling back here, any chance to review above?

**Comment by ericmustin** [comment]
As mentioned above, it's not possible to enable instrumentation in the `after_initialize` hook, (as Rails has already frozen the middleware that this point). The suggested  install steps can be found here: https://github.com/DataDog/dd-trace-rb/issues/1519#issuecomment-849056766.

Closing this, but feel free to open a new issue if there are any issues with the documented and supported installation path
