### ISSUE TITLE
Sidekiq Issues

### ISSUE THREAD

**Issue by sanjitsaluja** [DataDog/dd-trace-rb#155]
Notes:
- Running Sidekiq in Kubernetes.

We are seeing several Sidekiq threads get stuck with the following trace. It seems a deadlock. Anyone see issues like these running DataDog in sidekiq?

```
"/var/lib/gems/2.3.0/gems/ddtrace-0.7.2/lib/ddtrace/tracer.rb:203:in `synchronize'
/var/lib/gems/2.3.0/gems/ddtrace-0.7.2/lib/ddtrace/tracer.rb:203:in `record'
/var/lib/gems/2.3.0/gems/ddtrace-0.7.2/lib/ddtrace/span.rb:97:in `finish'
/var/lib/gems/2.3.0/gems/ddtrace-0.7.2/lib/ddtrace/span.rb:105:in `finish_at'
/var/lib/gems/2.3.0/gems/ddtrace-0.7.2/lib/ddtrace/contrib/rails/active_support.rb:109:in `trace_cache'
/var/lib/gems/2.3.0/gems/ddtrace-0.7.2/lib/ddtrace/contrib/rails/active_support.rb:35:in `block in instrument'
/var/lib/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/notifications/fanout.rb:127:in `finish'
/var/lib/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/notifications/fanout.rb:46:in `block in finish'
/var/lib/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/notifications/fanout.rb:46:in `each'
/var/lib/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/notifications/fanout.rb:46:in `finish'
/var/lib/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/notifications/instrumenter.rb:36:in `finish'
/var/lib/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/notifications/instrumenter.rb:25:in `instrument'
/var/lib/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/notifications.rb:164:in `instrument'
/var/lib/gems/2.3.0/gems/dalli-2.7.6/lib/active_support/cache/dalli_store.rb:371:in `instrument'
/var/lib/gems/2.3.0/gems/dalli-2.7.6/lib/active_support/cache/dalli_store.rb:101:in `fetch'
/var/lib/gems/2.3.0/gems/rails-settings-cached-0.6.4/lib/rails-settings/base.rb:36:in `[]'
/var/lib/gems/2.3.0/gems/rails-settings-cached-0.6.4/lib/rails-settings/settings.rb:32:in `rescue in method_missing'
/var/lib/gems/2.3.0/gems/rails-settings-cached-0.6.4/lib/rails-settings/settings.rb:22:in `method_missing'
/home/app/snappea/app/workers/feedback_email_scheduler.rb:14:in `block in perform'
/var/lib/gems/2.3.0/gems/activerecord-4.2.5/lib/active_record/relation/query_methods.rb:251:in `block in select'
/var/lib/gems/2.3.0/gems/activerecord-4.2.5/lib/active_record/relation/query_methods.rb:251:in `select'
/var/lib/gems/2.3.0/gems/activerecord-4.2.5/lib/active_record/relation/query_methods.rb:251:in `select'
/var/lib/gems/2.3.0/gems/activerecord-4.2.5/lib/active_record/querying.rb:10:in `select'
/home/app/snappea/app/workers/feedback_email_scheduler.rb:14:in `perform'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:167:in `execute_job'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:139:in `block (5 levels) in process'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq.rb:36:in `block in <module:Sidekiq>'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:135:in `block (4 levels) in process'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/home/app/snappea/lib/fooda/sidekiq/performance_indicator_server.rb:23:in `call'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/app/snappea/lib/fooda/sidekiq/async_failure_handler.rb:6:in `call'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/var/lib/gems/2.3.0/gems/sidekiq-status-0.6.0/lib/sidekiq-status/server_middleware.rb:37:in `call'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/var/lib/gems/2.3.0/gems/ddtrace-0.7.2/lib/ddtrace/contrib/sidekiq/tracer.rb:68:in `block in call'
/var/lib/gems/2.3.0/gems/ddtrace-0.7.2/lib/ddtrace/tracer.rb:185:in `trace'
/var/lib/gems/2.3.0/gems/ddtrace-0.7.2/lib/ddtrace/contrib/sidekiq/tracer.rb:61:in `call'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/var/lib/gems/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'
/var/lib/gems/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:363:in `perform_action_with_newrelic_trace'
/var/lib/gems/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/sidekiq.rb:29:in `call'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/var/lib/gems/2.3.0/gems/sidekiq-middleware-0.3.0/lib/sidekiq-middleware/server/unique_jobs.rb:18:in `call'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/var/lib/gems/2.3.0/gems/sidetiq-0.7.0/lib/sidetiq/middleware/history.rb:18:in `call_with_sidetiq_history'
/var/lib/gems/2.3.0/gems/sidetiq-0.7.0/lib/sidetiq/middleware/history.rb:6:in `call'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/var/lib/gems/2.3.0/gems/sidekiq-pro-3.3.1/lib/sidekiq/batch/middleware.rb:33:in `call'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/server/logging.rb:10:in `call'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/var/lib/gems/2.3.0/gems/sidekiq-failures-0.4.5/lib/sidekiq/failures/middleware.rb:9:in `call'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:134:in `block (3 levels) in process'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/logging.rb:32:in `with_context'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:183:in `stats'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:131:in `block in process'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq.rb:35:in `block in <module:Sidekiq>'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:126:in `process'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:82:in `process_one'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:70:in `run'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:17:in `watchdog'
/var/lib/gems/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:26:in `block in safe_thread'"
```

**Comment by ufoot** [comment]
Oh, that's bad indeed. Will try and reproduce the issue locally. Meanwhile, FYI, #145 changes quite a bit the way we transmit traces. More precisely https://github.com/DataDog/dd-trace-rb/pull/145/files#diff-968f743eeebc764c9c42cf2f4b286605R250 -> this `record` method does not "synchronizes" any more. At some point, yes, it's going to synchronize on some items, but not globally on the tracer as before. So you might be interested in that upcoming `0.8.0` release, it really could help.

**Comment by ufoot** [comment]
https://github.com/DataDog/dd-trace-rb/releases/tag/v0.8.0 is out, I suggest upgrading to it, it should really help fixing. At least, the blocking code mentioned above has been removed.

**Comment by sanjitsaluja** [comment]
Okay I'll try this out and reopen if necessary.
