### ISSUE TITLE
`Failed to apply Datadog::Contrib::Rails::Patcher patch` on development

### ISSUE THREAD

**Issue by luizkowalski** [DataDog/dd-trace-rb#1564]
I have the following class on `config/initializers/datadog.rb`

```ruby
require 'ddtrace'

Rails.application.reloader.to_prepare do
  # Disable APM on all instances except of web ones
  enable_apm = ENV['DYNO'].to_s.starts_with?('web.')

  default_service_name = "finiata-backend-#{AppSettings.current_region.downcase}-#{ENV['RAILS_ENV']}"
  service_name = ENV['HEROKU_APP_NAME'] || default_service_name

  # https://github.com/DataDog/dd-trace-rb/blob/master/docs/GettingStarted.md
  Datadog.configure do |c|
    c.tracer enabled: enable_apm

    # Different HTTP libraries
    c.use :excon, service_name: "#{service_name}-excon"
    c.use :faraday, split_by_domain: true
    c.use :http, service_name: "#{service_name}-http"

    # Everything else
    c.use :redis, service_name: "#{service_name}-redis"
    c.use :sidekiq, service_name: "#{service_name}-sidekiq", client_service_name: "#{service_name}-sidekiq-client"

    # And finally Rails, which will configure cache, postgres, etc.
    c.use :rails, service_name: service_name

    # Configure AR separately to properly set orm_service_name (defaults to always 'active_record')
    c.use :active_record, service_name: "#{service_name}-postgres", orm_service_name: "#{service_name}-active_record"
  end
end
```

When I start the server or the console, I get the following message:

```ruby
E, [2021-06-21T16:53:13.298322 #28635] ERROR -- ddtrace: [ddtrace] (/Users/luizkowalski/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/ddtrace-0.50.0/lib/ddtrace/contrib/patcher.rb:41:in `on_patch_error') Failed to apply Datadog::Contrib::Rails::Patcher patch. Cause: can't modify frozen Array: [Rack::MiniProfiler, ActionDispatch::HostAuthorization, Rack::Sendfile, ActionDispatch::Static, ActionDispatch::Executor, Sentry::Rails::CaptureExceptions, ActiveSupport::Cache::Strategy::LocalCache::Middleware, Rack::Runtime, Rack::MethodOverride, ActionDispatch::RequestId, RequestStore::Middleware, ActionDispatch::RemoteIp, Sprockets::Rails::QuietAssets, Rails::Rack::Logger, ActionDispatch::ShowExceptions, WebConsole::Middleware, ActionDispatch::DebugExceptions, ActionDispatch::ActionableExceptions, ActionDispatch::Reloader, ActionDispatch::Callbacks, ActionDispatch::Cookies, ActionDispatch::Session::CookieStore, ActionDispatch::Flash, ActionDispatch::ContentSecurityPolicy::Middleware, ActionDispatch::PermissionsPolicy::Middleware, Rack::Head, Rack::ConditionalGet, Rack::ETag, Rack::TempfileReaper, Warden::Manager, Remotipart::Middleware, Sentry::Rails::RescuedExceptionInterceptor, Flipper::Middleware::Memoizer, Bullet::Rack] Location: /Users/luizkowalski/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/stack.rb:102:in `insert'
```

It doesn't happen when I remove the `Rails.application.reloader.to_prepare do` lines (but I get a deprecation warning from `AppSettings` loading, which is what I'm trying to get rid of)

some older issues mention adding `require 'rake'` or `rails` but none of these helped so far.

I'm using ddtrace 0.50.0 with Rails 6.1.3.2 and Ruby 3.0.1

**Comment by luizkowalski** [comment]
oh, I JUST saw this (https://github.com/DataDog/dd-trace-rb/issues/1468)
makes sense, closing it
