### ISSUE TITLE
Datadog :rails configuration causes extremely slow local error pages

### ISSUE THREAD

**Issue by sgringwe** [DataDog/dd-trace-rb#1635]
In local development, the usage of :rails configuration on Datadog causes extremely slow error page renders. Page renders without any exceptions are not impacted.

The below configuration is an example of a very slow render - it is perfectly fast up until the point of error (for example, a method typo) at which point the rails server hits 100% CPU for 2-3 minutes, sometimes more, and finally renders the typical rails error page.

```
Datadog.configure do |c|
  c.use :rails
end

```

On the contrary, if I use the below initialization config, that 2-3 minute slowness does not occur:

```
Datadog.configure do |c|
end

```

Note: In reality the config file we run has additional configuration, but I simplified it down for the issue report. Completely avoiding the `Datadog.configure` call also is fine with no slowness.

Ruby: 2.7.2
Rails: 6.0.4
dd-trace-rb: 0.43 (also present on 0.51 during testing)

**Comment by marcotc** [comment]
👋 @sgringwe, thank you for this report.

I tried to reproduce your scenario but couldn't get the same behivour you encountered:

Using
```
Ruby: 2.7.2
Rails: 6.0.4
dd-trace-rb: 0.51.0
```

I did `rails _6.0.4_ new rails604`, then added `gem 'ddtrace', '0.51.0'` to the Gemfile file, `bundle install`, then added 
```ruby
require 'ddtrace'
Datadog.configure do |c|
  c.use :rails
end
```
to `config/initializers/ddtrace.rb`.

I then generate a test controller `rails generate scaffold test` and the `#index` method in `app/controllers/tests_controller.rb`:
```ruby
  def index
    raise 'oops' # I added this line
    @tests = Test.all
  end
```

I ran first time Rails migrations and webpack compilation, then started the application `bin/rails s`.

Visiting `http://localhost:3000/tests`, I immediately get the expected error page:

![Screen Shot 2021-08-06 at 1 45 05 PM](https://user-images.githubusercontent.com/583503/128569198-268605a5-741a-41c0-bcbd-274fe6a9c610.png)

I can tell that `ddtrace` is enabled because I get these log messages in my console when I visit the page:

```
RuntimeError (oops):

app/controllers/tests_controller.rb:6:in `index'
E, [2021-08-06T13:41:29.982783 #38435] ERROR -- ddtrace: [ddtrace] (/Users/marco.costa/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ddtrace-0.51.0/lib/ddtrace/transport/http/client.rb:35:in `rescue in send_request') Internal error during HTTP transport request. Cause: Failed to open TCP connection to 127.0.0.1:8126 (Connection refused - connect(2) for "127.0.0.1" port 8126) Location: /Users/marco.costa/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/http.rb:960:in `initialize'
I, [2021-08-06T13:41:29.984259 #38435]  INFO -- ddtrace: [ddtrace] DATADOG TRACER CONFIGURATION - {"date":"2021-08-06T13:41:29-07:00","os_name":"x86_64-apple-darwin19.6.0","version":"0.51.0","lang":"ruby","lang_version":"2.7.2","enabled":true,"service":"rails","agent_url":"http://127.0.0.1:8126?timeout=1","agent_error":"Datadog::Transport::InternalErrorResponse ok?: unsupported?:, not_found?:, client_error?:, server_error?:, internal_error?:true, payload:, error_type:Errno::ECONNREFUSED error:Failed to open TCP connection to 127.0.0.1:8126 (Connection refused - connect(2) for \"127.0.0.1\" port 8126)","debug":false,"analytics_enabled":false,"runtime_metrics_enabled":false,"integrations_loaded":"rails@6.0.4,rack@2.2.3,action_cable@6.0.4,active_support@6.0.4,action_pack@6.0.4,action_view@6.0.4,active_record@6.0.4","vm":"ruby-2.7.2","partial_flushing_enabled":false,"priority_sampling_enabled":false,"health_metrics_enabled":false,"integration_rails_analytics_enabled":"","integration_rails_analytics_sample_rate":"1.0","integration_rails_enabled":"true","integration_rails_service_name":"rails604default","integration_rails_cache_service":"rails604default-cache","integration_rails_controller_service":"rails604default","integration_rails_database_service":"rails604default-sqlite","integration_rails_distributed_tracing":"true","integration_rails_exception_controller":"","integration_rails_middlewa
re":"true","integration_rails_middleware_names":"false","integration_rails_template_base_path":"views/","integration_rails_log_injection":"false","integration_rack_analytics_enabled":"","integration_rack_analytics_sample_rate":"1.0","integration_rack_enabled":"true","integration_rack_service_name":"rails604default","integration_rack_application":"#\u003cRails604default::Application:0x00007f9d10a00e38\u003e","integration_rack_distributed_tracing":"true","integration_rack_headers":"{:response=\u003e[\"Content-Type\", \"X-Request-ID\"]}","integration_rack_middleware_names":"false","integration_rack_quantize":"{}","integration_rack_request_queuing":"false","integration_rack_web_service_name":"web-server","integration_action_cable_analytics_enabled":"false","integration_action_cable_analytics_sample_rate":"1.0","integration_action_cable_enabled":"true","integration_action_cable_service_name":"rails604default-action_cable","integration_active_support_analytics_enabled":"false","integration_active_support_analytics_sample_rate":"1.0","integration_active_support_enabled":"true","integration_active_support_service_name":"","integration_active_support_cache_service":"rails604default-cache","integration_action_pack_analytics_enabled":"","integration_action_pack_analytics_sample_rate":"1.0","integration_action_pack_enabled":"true","integration_action_pack_service_name":"rails604default","integration_action_pack_controller_service":"rails604default","integration_action_pack_exception_controller":"","integration_action_view_analytics_enabled":"false","integration_action_view_analytics_sample_rate":"1.0","integration_action_view_enabled":"true","integration_action_view_service_name":"rails604default","integration_action_view_template_base_path":"views/","integration_active_record_analytics_enabled":"false","integration_active_record_analytics_sample_rate":"1.0","integration_active_record_enabled":"true","integration_active_record_service_name":"rails604default-sqlite","integration_active_record_orm_service_name":""}
W, [2021-08-06T13:41:29.984416 #38435]  WARN -- ddtrace: [ddtrace] DATADOG TRACER DIAGNOSTIC - Agent Error: Datadog::Transport::InternalErrorResponse ok?: unsupported?:, not_found?:, client_error?:, server_error?:, internal_error?:true, payload:, error_type:Errno::ECONNREFUSED error:Failed to open TCP connection to 127.0.0.1:8126 (Connection refused - connect(2) for "127.0.0.1" port 8126)
```

(My agent wasn't running, but the controller request did get instrumented, based on the logs above. It just didn't get successfully flushed.)

Let me know if you think I'm missing something in my setup.

**Comment by sgringwe** [comment]
Thank you @marcotc . It appears that there is a mix of things causing this. I'll close this for now but re-open if I have more details.
