### ISSUE TITLE
Sinatra integration does not respect DD_SERVICE configuration

### ISSUE THREAD

**Issue by ivoanjo** [DataDog/dd-trace-rb#1646]
Unlike other integrations, setting `DD_SERVICE` (or `Datadog.configure { |c| c.service = '...' }`) does not make sinatra top-level traces use the configured service name (instead they just use `sinatra`).

This really confused me as I was looking for my traces under the configured service name, and nothing was coming up.

Test case:

```ruby
$ cat example-sinatra.rb
require 'sinatra'
require 'ddtrace'

Datadog.configure do |c|
  c.use :sinatra
  c.service = 'test'
  c.diagnostics.debug = true
end

get '/foo' do
  'foo'
end
```

output (run + curl from another shell):

```
$ bundle exec ruby example-sinatra.rb
[2021-08-11 14:15:16] INFO  WEBrick 1.6.1
[2021-08-11 14:15:16] INFO  ruby 2.7.4 (2021-07-07) [x86_64-darwin19]
== Sinatra (v2.1.0) has taken the stage on 4567 for development with backup from WEBrick
[2021-08-11 14:15:16] INFO  WEBrick::HTTPServer#start: pid=55380 port=4567
D, [2021-08-11T14:15:40.185571 #55380] DEBUG -- ddtrace: [ddtrace] (dd-trace-rb/lib/ddtrace/tracer.rb:363:in `write') Writing 2 spans (enabled: true)
D, [2021-08-11T14:15:40.186010 #55380] DEBUG -- ddtrace: [ddtrace] (dd-trace-rb/lib/ddtrace/tracer.rb:366:in `write') [
 Name: sinatra.request
Span ID: 3071946997650091277
Parent ID: 0
Trace ID: 4088973163050907135
Type: web
Service: sinatra
Resource: GET /foo
Error: 0
Start: 1628687740180781056
End: 1628687740185491968
Duration: 0.004709000000730157
Allocations: 893
Tags: [
   runtime-id => 7c3192f1-e1ce-44ed-a4a2-b7058d91e377,
   sinatra.route.path => /foo,
   http.url => /foo,
   http.method => GET,
   sinatra.app.name => Sinatra::Application,
   http.status_code => 200,
   http.response.headers.content_type => text/html;charset=utf-8]
Metrics: [
   _dd.agent_psr => 1.0,
   system.pid => 55380.0,
   _dd.measured => 1.0,
   _sampling_priority_v1 => 1.0],

 Name: sinatra.route
Span ID: 2486434189580784802
Parent ID: 3071946997650091277
Trace ID: 4088973163050907135
Type: web
Service: sinatra
Resource: GET /foo
Error: 0
Start: 1628687740182778880
End: 1628687740182830080
Duration: 4.900000203633681e-05
Allocations: 8
Tags: [
   sinatra.app.name => Sinatra::Application,
   sinatra.route.path => /foo]
Metrics: [ _dd.measured => 1.0]]

::1 - - [11/Aug/2021:14:15:40 +0100] "GET /foo HTTP/1.1" 200 3 0.0077
::1 - - [11/Aug/2021:14:15:40 BST] "GET /foo HTTP/1.1" 200 3
- -> /foo
```

**Comment by lloeki** [comment]
Should be fixed on master / 1.0.0.beta1, correct?
