### ISSUE TITLE
Redis stack level too deep

### ISSUE THREAD

**Issue by exadeci** [DataDog/dd-trace-rb#1686]
Adding 
`  gem 'ddtrace', require: 'ddtrace/auto_instrument'`

To our Gemfile creates an error while it tries to load Redis and dd-trace-rb only works if we set `DD_TRACE_REDIS_ENABLED=false`

Here's an output of the issue:

```
=> Booting WEBrick
=> Rails 6.1.4 application starting in development http://localhost:3000
=> Run `bin/rails server --help` for more startup options
`Redis#exists(key)` will return an Integer by default in redis-rb 4.3. The option to explicitly disable this behaviour via `Redis.exists_returns_integer` will be removed in 5.0. You should use `exists?` instead.
Exiting
I, [2021-09-15T11:04:45.516913 #37698]  INFO -- ddtrace: [ddtrace] DATADOG TRACER CONFIGURATION - {"date":"2021-09-15T11:04:45+10:00","os_name":"x86_64-apple-darwin19.6.0","version":"0.52.0","lang":"ruby","lang_version":"2.7.2","enabled":true,"service":"rails","agent_url":"http://127.0.0.1:8126?timeout=1","debug":false,"analytics_enabled":false,"runtime_metrics_enabled":false,"integrations_loaded":"active_model_serializers@,aws@3.119.0,concurrent_ruby@1.1.9,dalli@,delayed_job@,elasticsearch@,ethon@,excon@0.85.0,faraday@1.7.0,grape@,graphql@,grpc@,http@2.7.2,httpclient@,httprb@,kafka@,mongo@,mysql2@,presto@,qless@,que@,racecar@,rails@6.1.4,rake@13.0.6,redis@4.4.0,resque@,rest_client@,sequel@,shoryuken@,sidekiq@6.2.1,sinatra@,sneakers@,sucker_punch@","vm":"ruby-2.7.2","partial_flushing_enabled":false,"priority_sampling_enabled":false,"health_metrics_enabled":false,"integration_active_model_serializers_analytics_enabled":"false","integration_active_model_serializers_analytics_sample_rate":"1.0","integration_active_model_serializers_enabled":"true","integration_active_model_serializers_service_name":"active_model_serializers","integration_aws_analytics_enabled":"false","integration_aws_analytics_sample_rate":"1.0","integration_aws_enabled":"true","integration_aws_service_name":"aws","integration_concurrent_ruby_analytics_enabled":"false","integration_concurrent_ruby_analytics_sample_rate":"1.0","integration_concurrent_ruby_enabled":"true","integration_concurrent_ruby_service_name":"concurrent-ruby","integration_dalli_analytics_enabled":"false","integration_dalli_analytics_sample_rate":"1.0","integration_dalli_enabled":"true","integration_dalli_service_name":"memcached","integration_delayed_job_analytics_enabled":"false","integration_delayed_job_analytics_sample_rate":"1.0","integration_delayed_job_enabled":"true","integration_delayed_job_service_name":"delayed_job","integration_delayed_job_client_service_name":"delayed_job-client","integration_delayed_job_error_handler":"#\u003cProc:0x00007f88a482d5a0 /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ddtrace-0.52.0/lib/ddtrace/tracer.rb:33\u003e","integration_elasticsearch_analytics_enabled":"false","integration_elasticsearch_analytics_sample_rate":"1.0","integration_elasticsearch_enabled":"true","integration_elasticsearch_service_name":"elasticsearch","integration_elasticsearch_quantize":"{}","integration_ethon_analytics_enabled":"false","integration_ethon_analytics_sample_rate":"1.0","integration_ethon_enabled":"true","integration_ethon_service_name":"ethon","integration_ethon_distributed_tracing":"true","integration_ethon_split_by_domain":"false","integration_excon_analytics_enabled":"false","integration_excon_analytics_sample_rate":"1.0","integration_excon_enabled":"true","integration_excon_service_name":"excon","integration_excon_distributed_tracing":"true","integration_excon_error_handler":"","integration_excon_split_by_domain":"false","integration_faraday_analytics_enabled":"false","integration_faraday_analytics_sample_rate":"1.0","integration_faraday_enabled":"true","integration_faraday_service_name":"faraday","integration_faraday_distributed_tracing":"true","integration_faraday_error_handler":"#\u003cProc:0x00007f8915b9c490 /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ddtrace-0.52.0/lib/ddtrace/contrib/faraday/configuration/settings.rb:12 (lambda)\u003e","integration_faraday_split_by_domain":"false","integration_grape_analytics_enabled":"","integration_grape_analytics_sample_rate":"1.0","integration_grape_enabled":"true","integration_grape_service_name":"grape","integration_grape_error_statuses":"","integration_graphql_analytics_enabled":"","integration_graphql_analytics_sample_rate":"1.0","integration_graphql_enabled":"true","integration_graphql_service_name":"ruby-graphql","integration_graphql_schemas":"","integration_grpc_analytics_enabled":"false","integration_grpc_analytics_sample_rate":"1.0","integration_grpc_enabled":"true","integration_grpc_service_name":"grpc","integration_grpc_error_handler":"#\u003cProc:0x00007f88a482d5a0 /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ddtrace-0.52.0/lib/ddtrace/tracer.rb:33\u003e","integration_http_analytics_enabled":"false","integration_http_analytics_sample_rate":"1.0","integration_http_enabled":"true","integration_http_service_name":"net/http","integration_http_distributed_tracing":"true","integration_http_split_by_domain":"false","integration_httpclient_analytics_enabled":"false","integration_httpclient_analytics_sample_rate":"1.0","integration_httpclient_enabled":"true","integration_httpclient_service_name":"httpclient","integration_httpclient_distributed_tracing":"true","integration_httpclient_split_by_domain":"false","integration_httprb_analytics_enabled":"false","integration_httprb_analytics_sample_rate":"1.0","integration_httprb_enabled":"true","integration_httprb_service_name":"httprb","integration_httprb_distributed_tracing":"true","integration_httprb_split_by_domain":"false","integration_kafka_analytics_enabled":"false","integration_kafka_analytics_sample_rate":"1.0","integration_kafka_enabled":"true","integration_kafka_service_name":"kafka","integration_mongo_analytics_enabled":"false","integration_mongo_analytics_sample_rate":"1.0","integration_mongo_enabled":"true","integration_mongo_service_name":"mongodb","integration_mongo_quantize":"{:show=\u003e[:collection, :database, :operation]}","integration_mysql2_analytics_enabled":"false","integration_mysql2_analytics_sample_rate":"1.0","integration_mysql2_enabled":"true","integration_mysql2_service_name":"mysql2","integration_presto_analytics_enabled":"false","integration_presto_analytics_sample_rate":"1.0","integration_presto_enabled":"true","integration_presto_service_name":"presto","integration_qless_analytics_enabled":"false","integration_qless_analytics_sample_rate":"1.0","integration_qless_enabled":"true","integration_qless_service_name":"qless","integration_qless_tag_job_data":"false","integration_qless_tag_job_tags":"false","integration_que_analytics_enabled":"false","integration_que_analytics_sample_rate":"1.0","integration_que_enabled":"true","integration_que_service_name":"que","integration_que_distributed_tracing":"true","integration_que_tag_args":"false","integration_que_tag_data":"false","integration_que_error_handler":"#\u003cProc:0x00007f88a482d5a0 /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ddtrace-0.52.0/lib/ddtrace/tracer.rb:33\u003e","integration_racecar_analytics_enabled":"false","integration_racecar_analytics_sample_rate":"1.0","integration_racecar_enabled":"true","integration_racecar_service_name":"racecar","integration_rails_analytics_enabled":"","integration_rails_analytics_sample_rate":"1.0","integration_rails_enabled":"true","integration_rails_service_name":"","integration_rails_cache_service":"","integration_rails_controller_service":"","integration_rails_database_service":"","integration_rails_distributed_tracing":"true","integration_rails_exception_controller":"","integration_rails_middleware":"true","integration_rails_middleware_names":"false","integration_rails_template_base_path":"views/","integration_rails_log_injection":"false","integration_rake_analytics_enabled":"false","integration_rake_analytics_sample_rate":"1.0","integration_rake_enabled":"true","integration_rake_service_name":"rake","integration_rake_quantize":"{}","integration_redis_analytics_enabled":"false","integration_redis_analytics_sample_rate":"0.0","integration_redis_enabled":"true","integration_redis_service_name":"redis","integration_redis_command_args":"true","integration_resque_analytics_enabled":"false","integration_resque_analytics_sample_rate":"1.0","integration_resque_enabled":"true","integration_resque_service_name":"resque","integration_resque_workers":"","integration_resque_error_handler":"#\u003cProc:0x00007f88a482d5a0 /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ddtrace-0.52.0/lib/ddtrace/tracer.rb:33\u003e","integration_rest_client_analytics_enabled":"false","integration_rest_client_analytics_sample_rate":"1.0","integration_rest_client_enabled":"true","integration_rest_client_service_name":"rest_client","integration_rest_client_distributed_tracing":"true","integration_sequel_analytics_enabled":"false","integration_sequel_analytics_sample_rate":"1.0","integration_sequel_enabled":"true","integration_sequel_service_name":"","integration_shoryuken_analytics_enabled":"false","integration_shoryuken_analytics_sample_rate":"1.0","integration_shoryuken_enabled":"true","integration_shoryuken_service_name":"shoryuken","integration_shoryuken_error_handler":"#\u003cProc:0x00007f88a482d5a0 /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ddtrace-0.52.0/lib/ddtrace/tracer.rb:33\u003e","integration_shoryuken_tag_body":"false","integration_sidekiq_analytics_enabled":"false","integration_sidekiq_analytics_sample_rate":"1.0","integration_sidekiq_enabled":"true","integration_sidekiq_service_name":"sidekiq","integration_sidekiq_tag_args":"false","integration_sidekiq_client_service_name":"sidekiq-client","integration_sidekiq_error_handler":"#\u003cProc:0x00007f88a482d5a0 /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ddtrace-0.52.0/lib/ddtrace/tracer.rb:33\u003e","integration_sinatra_analytics_enabled":"","integration_sinatra_analytics_sample_rate":"1.0","integration_sinatra_enabled":"true","integration_sinatra_service_name":"sinatra","integration_sinatra_distributed_tracing":"true","integration_sinatra_headers":"{:response=\u003e[\"Content-Type\", \"X-Request-ID\"]}","integration_sinatra_resource_script_names":"false","integration_sneakers_analytics_enabled":"false","integration_sneakers_analytics_sample_rate":"1.0","integration_sneakers_enabled":"true","integration_sneakers_service_name":"sneakers","integration_sneakers_error_handler":"#\u003cProc:0x00007f88a482d5a0 /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ddtrace-0.52.0/lib/ddtrace/tracer.rb:33\u003e","integration_sneakers_tag_body":"false","integration_sucker_punch_analytics_enabled":"false","integration_sucker_punch_analytics_sample_rate":"1.0","integration_sucker_punch_enabled":"true","integration_sucker_punch_service_name":"sucker_punch"}
Traceback (most recent call last):
	10159: from bin/rails:5:in `<main>'
	10158: from /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	10157: from /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	10156: from /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	10155: from /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	10154: from /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	10153: from /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.4/lib/rails/commands.rb:18:in `<main>'
	10152: from /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.4/lib/rails/command.rb:48:in `invoke'
	 ... 10147 levels...
	    4: from /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ddtrace-0.52.0/lib/ddtrace/contrib/extensions.rb:106:in `[]'
	    3: from /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ddtrace-0.52.0/lib/ddtrace/contrib/configurable.rb:51:in `resolve'
	    2: from /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ddtrace-0.52.0/lib/ddtrace/contrib/redis/configuration/resolver.rb:14:in `resolve'
	    1: from /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ddtrace-0.52.0/lib/ddtrace/contrib/redis/configuration/resolver.rb:22:in `parse_matcher'
/Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ddtrace-0.52.0/lib/ddtrace/contrib/redis/vendor/resolver.rb:39:in `resolve': stack level too deep (SystemStackError)
```

**Comment by marcotc** [comment]
👋 @exadeci, thank you for this bug report.

I wasn't able to reproduce it with a simple Rails application + Redis.

I noticed that there's no repeating pattern in the stack trace you provided. I understand that you can't provide the whole `SystemStackError` error output, as it is too large, but would you be able to provide to us the part of the stack trace where it shows a repeating pattern?

**Comment by exadeci** [comment]
@marcotc That's all the output I get nothing repeating really:

```
=> Booting WEBrick
=> Rails 6.1.4 application starting in development http://localhost:3000
=> Run `bin/rails server --help` for more startup options
`Redis#exists(key)` will return an Integer by default in redis-rb 4.3. The option to explicitly disable this behaviour via `Redis.exists_returns_integer` will be removed in 5.0. You should use `exists?` instead.
Exiting
I, [2021-09-18T14:12:13.972184 #46668]  INFO -- ddtrace: [ddtrace] DATADOG TRACER CONFIGURATION - {"date":"2021-09-18T14:12:13+10:00","os_name":"x86_64-apple-darwin19.6.0","version":"0.52.0","lang":"ruby","lang_version":"2.7.2","enabled":true,"service":"rails","agent_url":"http://127.0.0.1:8126?timeout=1","debug":false,"analytics_enabled":false,"runtime_metrics_enabled":false,"integrations_loaded":"active_model_serializers@,aws@3.119.0,concurrent_ruby@1.1.9,dalli@,delayed_job@,elasticsearch@,ethon@,excon@0.85.0,faraday@1.7.0,grape@,graphql@,grpc@,http@2.7.2,httpclient@,httprb@,kafka@,mongo@,mysql2@,presto@,qless@,que@,racecar@,rails@6.1.4,rake@13.0.6,redis@4.4.0,resque@,rest_client@,sequel@,shoryuken@,sidekiq@6.2.1,sinatra@,sneakers@,sucker_punch@","vm":"ruby-2.7.2","partial_flushing_enabled":false,"priority_sampling_enabled":false,"health_metrics_enabled":false,"integration_active_model_serializers_analytics_enabled":"false","integration_active_model_serializers_analytics_sample_rate":"1.0","integration_active_model_serializers_enabled":"true","integration_active_model_serializers_service_name":"active_model_serializers","integration_aws_analytics_enabled":"false","integration_aws_analytics_sample_rate":"1.0","integration_aws_enabled":"true","integration_aws_service_name":"aws","integration_concurrent_ruby_analytics_enabled":"false","integration_concurrent_ruby_analytics_sample_rate":"1.0","integration_concurrent_ruby_enabled":"true","integration_concurrent_ruby_service_name":"concurrent-ruby","integration_dalli_analytics_enabled":"false","integration_dalli_analytics_sample_rate":"1.0","integration_dalli_enabled":"true","integration_dalli_service_name":"memcached","integration_delayed_job_analytics_enabled":"false","integration_delayed_job_analytics_sample_rate":"1.0","integration_delayed_job_enabled":"true","integration_delayed_job_service_name":"delayed_job","integration_delayed_job_client_service_name":"delayed_job-client","integration_delayed_job_error_handler":"#\u003cProc:0x00007f9ecebc4930 /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ddtrace-0.52.0/lib/ddtrace/tracer.rb:33\u003e","integration_elasticsearch_analytics_enabled":"false","integration_elasticsearch_analytics_sample_rate":"1.0","integration_elasticsearch_enabled":"true","integration_elasticsearch_service_name":"elasticsearch","integration_elasticsearch_quantize":"{}","integration_ethon_analytics_enabled":"false","integration_ethon_analytics_sample_rate":"1.0","integration_ethon_enabled":"true","integration_ethon_service_name":"ethon","integration_ethon_distributed_tracing":"true","integration_ethon_split_by_domain":"false","integration_excon_analytics_enabled":"false","integration_excon_analytics_sample_rate":"1.0","integration_excon_enabled":"true","integration_excon_service_name":"excon","integration_excon_distributed_tracing":"true","integration_excon_error_handler":"","integration_excon_split_by_domain":"false","integration_faraday_analytics_enabled":"false","integration_faraday_analytics_sample_rate":"1.0","integration_faraday_enabled":"true","integration_faraday_service_name":"faraday","integration_faraday_distributed_tracing":"true","integration_faraday_error_handler":"#\u003cProc:0x00007f9e8b98aab8 /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ddtrace-0.52.0/lib/ddtrace/contrib/faraday/configuration/settings.rb:12 (lambda)\u003e","integration_faraday_split_by_domain":"false","integration_grape_analytics_enabled":"","integration_grape_analytics_sample_rate":"1.0","integration_grape_enabled":"true","integration_grape_service_name":"grape","integration_grape_error_statuses":"","integration_graphql_analytics_enabled":"","integration_graphql_analytics_sample_rate":"1.0","integration_graphql_enabled":"true","integration_graphql_service_name":"ruby-graphql","integration_graphql_schemas":"","integration_grpc_analytics_enabled":"false","integration_grpc_analytics_sample_rate":"1.0","integration_grpc_enabled":"true","integration_grpc_service_name":"grpc","integration_grpc_error_handler":"#\u003cProc:0x00007f9ecebc4930 /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ddtrace-0.52.0/lib/ddtrace/tracer.rb:33\u003e","integration_http_analytics_enabled":"false","integration_http_analytics_sample_rate":"1.0","integration_http_enabled":"true","integration_http_service_name":"net/http","integration_http_distributed_tracing":"true","integration_http_split_by_domain":"false","integration_httpclient_analytics_enabled":"false","integration_httpclient_analytics_sample_rate":"1.0","integration_httpclient_enabled":"true","integration_httpclient_service_name":"httpclient","integration_httpclient_distributed_tracing":"true","integration_httpclient_split_by_domain":"false","integration_httprb_analytics_enabled":"false","integration_httprb_analytics_sample_rate":"1.0","integration_httprb_enabled":"true","integration_httprb_service_name":"httprb","integration_httprb_distributed_tracing":"true","integration_httprb_split_by_domain":"false","integration_kafka_analytics_enabled":"false","integration_kafka_analytics_sample_rate":"1.0","integration_kafka_enabled":"true","integration_kafka_service_name":"kafka","integration_mongo_analytics_enabled":"false","integration_mongo_analytics_sample_rate":"1.0","integration_mongo_enabled":"true","integration_mongo_service_name":"mongodb","integration_mongo_quantize":"{:show=\u003e[:collection, :database, :operation]}","integration_mysql2_analytics_enabled":"false","integration_mysql2_analytics_sample_rate":"1.0","integration_mysql2_enabled":"true","integration_mysql2_service_name":"mysql2","integration_presto_analytics_enabled":"false","integration_presto_analytics_sample_rate":"1.0","integration_presto_enabled":"true","integration_presto_service_name":"presto","integration_qless_analytics_enabled":"false","integration_qless_analytics_sample_rate":"1.0","integration_qless_enabled":"true","integration_qless_service_name":"qless","integration_qless_tag_job_data":"false","integration_qless_tag_job_tags":"false","integration_que_analytics_enabled":"false","integration_que_analytics_sample_rate":"1.0","integration_que_enabled":"true","integration_que_service_name":"que","integration_que_distributed_tracing":"true","integration_que_tag_args":"false","integration_que_tag_data":"false","integration_que_error_handler":"#\u003cProc:0x00007f9ecebc4930 /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ddtrace-0.52.0/lib/ddtrace/tracer.rb:33\u003e","integration_racecar_analytics_enabled":"false","integration_racecar_analytics_sample_rate":"1.0","integration_racecar_enabled":"true","integration_racecar_service_name":"racecar","integration_rails_analytics_enabled":"","integration_rails_analytics_sample_rate":"1.0","integration_rails_enabled":"true","integration_rails_service_name":"","integration_rails_cache_service":"","integration_rails_controller_service":"","integration_rails_database_service":"","integration_rails_distributed_tracing":"true","integration_rails_exception_controller":"","integration_rails_middleware":"true","integration_rails_middleware_names":"false","integration_rails_template_base_path":"views/","integration_rails_log_injection":"false","integration_rake_analytics_enabled":"false","integration_rake_analytics_sample_rate":"1.0","integration_rake_enabled":"true","integration_rake_service_name":"rake","integration_rake_quantize":"{}","integration_redis_analytics_enabled":"false","integration_redis_analytics_sample_rate":"1.0","integration_redis_enabled":"true","integration_redis_service_name":"redis","integration_redis_command_args":"true","integration_resque_analytics_enabled":"false","integration_resque_analytics_sample_rate":"1.0","integration_resque_enabled":"true","integration_resque_service_name":"resque","integration_resque_workers":"","integration_resque_error_handler":"#\u003cProc:0x00007f9ecebc4930 /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ddtrace-0.52.0/lib/ddtrace/tracer.rb:33\u003e","integration_rest_client_analytics_enabled":"false","integration_rest_client_analytics_sample_rate":"1.0","integration_rest_client_enabled":"true","integration_rest_client_service_name":"rest_client","integration_rest_client_distributed_tracing":"true","integration_sequel_analytics_enabled":"false","integration_sequel_analytics_sample_rate":"1.0","integration_sequel_enabled":"true","integration_sequel_service_name":"","integration_shoryuken_analytics_enabled":"false","integration_shoryuken_analytics_sample_rate":"1.0","integration_shoryuken_enabled":"true","integration_shoryuken_service_name":"shoryuken","integration_shoryuken_error_handler":"#\u003cProc:0x00007f9ecebc4930 /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ddtrace-0.52.0/lib/ddtrace/tracer.rb:33\u003e","integration_shoryuken_tag_body":"false","integration_sidekiq_analytics_enabled":"false","integration_sidekiq_analytics_sample_rate":"1.0","integration_sidekiq_enabled":"true","integration_sidekiq_service_name":"sidekiq","integration_sidekiq_tag_args":"false","integration_sidekiq_client_service_name":"sidekiq-client","integration_sidekiq_error_handler":"#\u003cProc:0x00007f9ecebc4930 /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ddtrace-0.52.0/lib/ddtrace/tracer.rb:33\u003e","integration_sinatra_analytics_enabled":"","integration_sinatra_analytics_sample_rate":"1.0","integration_sinatra_enabled":"true","integration_sinatra_service_name":"sinatra","integration_sinatra_distributed_tracing":"true","integration_sinatra_headers":"{:response=\u003e[\"Content-Type\", \"X-Request-ID\"]}","integration_sinatra_resource_script_names":"false","integration_sneakers_analytics_enabled":"false","integration_sneakers_analytics_sample_rate":"1.0","integration_sneakers_enabled":"true","integration_sneakers_service_name":"sneakers","integration_sneakers_error_handler":"#\u003cProc:0x00007f9ecebc4930 /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ddtrace-0.52.0/lib/ddtrace/tracer.rb:33\u003e","integration_sneakers_tag_body":"false","integration_sucker_punch_analytics_enabled":"false","integration_sucker_punch_analytics_sample_rate":"1.0","integration_sucker_punch_enabled":"true","integration_sucker_punch_service_name":"sucker_punch"}
Traceback (most recent call last):
	10159: from bin/rails:5:in `<main>'
	10158: from /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	10157: from /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	10156: from /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	10155: from /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	10154: from /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	10153: from /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.4/lib/rails/commands.rb:18:in `<main>'
	10152: from /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.4/lib/rails/command.rb:48:in `invoke'
	 ... 10147 levels...
	    4: from /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ddtrace-0.52.0/lib/ddtrace/contrib/extensions.rb:106:in `[]'
	    3: from /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ddtrace-0.52.0/lib/ddtrace/contrib/configurable.rb:51:in `resolve'
	    2: from /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ddtrace-0.52.0/lib/ddtrace/contrib/redis/configuration/resolver.rb:14:in `resolve'
	    1: from /Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ddtrace-0.52.0/lib/ddtrace/contrib/redis/configuration/resolver.rb:22:in `parse_matcher'
/Users/gaetan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ddtrace-0.52.0/lib/ddtrace/contrib/redis/vendor/resolver.rb:39:in `resolve': stack level too deep (SystemStackError)
```
