### ISSUE TITLE
ActiveSupport patcher fails with "uninitialized constant ActiveSupport::Cache" when ActiveSupport is loaded piecemeal

### ISSUE THREAD

**Issue by ivoanjo** [DataDog/dd-trace-rb#1689]
I was just testing out a simple grape app and run into this issue:

```
E, [2021-09-16T14:56:43.874955 #26933] ERROR -- ddtrace: [ddtrace] (/Users/ivo.anjo/.rvm/gems/ruby-
2.7.4/gems/ddtrace-0.52.0/lib/ddtrace/contrib/patcher.rb:42:in `on_patch_error') Failed to apply 
Datadog::Contrib::ActiveSupport::Cache::Patcher patch. Cause: uninitialized constant 
ActiveSupport::Cache Location: /Users/ivo.anjo/.rvm/gems/ruby-2.7.4/gems/ddtrace-
0.52.0/lib/ddtrace/contrib/active_support/cache/patcher.rb:30:in `cache_store_class'
```

 Reproducing it is as simple as running:

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'ddtrace'
  gem 'grape'
end

require 'grape'
require 'ddtrace/auto_instrument'
```

The issue seems to be caused by `grape` using ActiveSupport in a very minimalistic way:

https://github.com/ruby-grape/grape/blob/5b4a2dd51ce998a13c368218b228d78665097539/lib/grape.rb#L10-L22

...rather than just going `require 'active_support'`.

This causes our ActiveSupport integration to decide it can patch (because `ActiveSupport` is indeed available and at least partly loaded), but then fail because `ActiveSupport::Cache` isn't actually loaded.

I decided to open this issue rather than fixing it myself as I'm not quite sure what the best fix is. Should we not try to patch `ActiveSupport` if the cache is not loaded? Should we just `require 'active_support/cache'`? Something else?

**Comment by ivoanjo** [comment]
Can no longer reproduce, closing :)
