### ISSUE TITLE
config.ru:5:in `require': cannot load such file -- ddtrace/profiling/preload (LoadError)   

### ISSUE THREAD

**Issue by dfuentes77** [DataDog/dd-trace-rb#1698]
I got this after a Rails 5.2.5->5.2.6 only upgrade.  Puma was not upgraded.  We use `prune_bundler` so I didn't expect this behavior.  We had to restart the pumas to get passed this error.  Please advise.

**Comment by ivoanjo** [comment]
Hey @dfuentes77, thanks for getting in touch (and for using dd-trace-rb!)

For me to investigate further, could you provide the following information:

1. How your service has been onboarded to use profiler (e.g. step 5 from [the installation instructions](https://docs.datadoghq.com/tracing/profiler/enabling/ruby/)): are you using `ddtracerb exec`? Or did you modify your `config.ru`?

2. Can you share the relevant part of `config.ru` that triggered the issue?

3. Can you share your `Gemfile.lock`/`gems.locked` or if not possible, can you describe which versions of puma, ddtrace and Ruby you're using?

4. Can you describe in more detail what commands you ran that triggered the error, and what you did to fix it? From your description, it sounds like you were perhaps doing [puma restart](https://github.com/puma/puma/blob/master/docs/restart.md)?

**Comment by dfuentes77** [comment]
1,2. Yes, using **config.ru** option:
```
require 'ddtrace/profiling/preload'
require ::File.expand_path('../config/environment', __FILE__)
run Rails.application
```
3. Using ruby 2.5.1, the relevant section of Gemfile.lock:
```
    ddtrace (0.51.1)
      ffi (~> 1.0)
      msgpack
...
    dogstatsd-ruby (5.2.0)
...
    google-protobuf (3.17.3)
...
    puma (5.2.2)
```

4. Relevant parts of systemd file:
```
ExecStart=/usr/local/rbenv/shims/bundle exec puma -e ${RAILS_ENV} config.ru
ExecReload=/bin/kill -s USR1 $MAINPID
```
and process was restarted with reload command to do a phased restart

Relevant puma config:
```
threads 5, 5
workers Etc.nprocessors / 2
preload_app! false
prune_bundler
```

Full stack trace:
```
config.ru:5:in `require': cannot load such file -- ddtrace/profiling/preload (LoadError)
        from config.ru:5:in `block in <main>'
        from <full path to puma-5.2.2 gem>/lib/puma/rack/builder.rb:186:in `instance_eval'
        from <full path to puma-5.2.2 gem>/lib/puma/rack/builder.rb:186:in `initialize'
        from config.ru:in `new'
        from config.ru:in `<main>'
        from <full path to puma-5.2.2 gem>/lib/puma/rack/builder.rb:172:in `eval'
        from <full path to puma-5.2.2 gem>/lib/puma/rack/builder.rb:172:in `new_from_string'
        from <full path to puma-5.2.2 gem>/lib/puma/rack/builder.rb:163:in `parse_file'
        from <full path to puma-5.2.2 gem>/lib/puma/configuration.rb:344:in `load_rackup'
        from <full path to puma-5.2.2 gem>/lib/puma/configuration.rb:266:in `app'
        from <full path to puma-5.2.2 gem>/lib/puma/runner.rb:154:in `app'
        from <full path to puma-5.2.2 gem>/lib/puma/runner.rb:158:in `start_server'
        from <full path to puma-5.2.2 gem>/lib/puma/cluster/worker.rb:57:in `run'
        from <full path to puma-5.2.2 gem>/lib/puma/cluster.rb:195:in `worker'
        from <full path to puma-5.2.2 gem>/lib/puma/cluster.rb:96:in `block in spawn_worker'
        from <full path to puma-5.2.2 gem>/lib/puma/cluster.rb:96:in `fork'
        from <full path to puma-5.2.2 gem>/lib/puma/cluster.rb:96:in `spawn_worker'
        from <full path to puma-5.2.2 gem>/lib/puma/cluster.rb:78:in `block in spawn_workers'
        from <full path to puma-5.2.2 gem>/lib/puma/cluster.rb:71:in `times'
        from <full path to puma-5.2.2 gem>/lib/puma/cluster.rb:71:in `spawn_workers'
        from <full path to puma-5.2.2 gem>/lib/puma/cluster.rb:142:in `check_workers'
        from <full path to puma-5.2.2 gem>/lib/puma/cluster.rb:414:in `run'
        from <full path to puma-5.2.2 gem>/lib/puma/launcher.rb:181:in `run'
        from <full path to puma-5.2.2 gem>/lib/puma/cli.rb:80:in `run'
        from <full path to puma-5.2.2 gem>/bin/puma-wild:25:in `<main>'
config.ru:5:in `require': cannot load such file -- ddtrace/profiling/preload (LoadError)
```

Another note that I'm curious might be related:  we have a custom/private gem we build/use that also uses rails and also was upgraded from 5.2.5 -> 5.2.6, as part of the deployment and phased-restart of the puma that resulted in these errors and puma getting stuck on this.  Only rails 5.2.5->5.2.6 was upgraded in that gem as well.  

Let me know if you need anything else to help in the investigation.   Thanks!

**Comment by ivoanjo** [comment]
Thanks for the info. I've spent some time trying to reproduce it using both Rails and Sinatra, and the Ruby/gem versions you shared and I couldn't; even tried upgrading dd-trace-rb and doing the phased-restart and puma would pick up the new version.

1. One interesting thing that your stack trace hints at is that puma is using it's "built-in" rack support, not the rack gem. And that's interesting because only in a very stripped down Rails setup can you run without rack (at least in my experiments, half of Rails directly or indirectly pulled the rack gem).
  
    Could you confirm if that's the case?

2. Are you able to reproduce this issue locally, or in a new/empty Rails app with a similar Gemfile? This would allow us to see if your production environment affects this issue, or if happens anywhere your test app/an empty Rails app with the same configuration is run.

**Comment by ivoanjo** [comment]
👍  do let me know if you run into further issues (and any other feedback -- negative and positive about the profiler :D)
