### ISSUE TITLE
Gem Load Error for Rails when ActiveRecord is disabled

### ISSUE THREAD

**Issue by rsullivan-gpsw** [DataDog/dd-trace-rb#172]
I have a Rails application that uses dynamodb instead of ActiveRecord. I have disabled active record by commenting it out in `application.rb`. This works fine with the `0.7` versions of ddtrace, but when I upgrade to `0.8.0` I get the following error.

```
Gem Load Error is: uninitialized constant ActiveRecord
Did you mean?  ActiveModel
Backtrace for gem load error is:
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ddtrace-0.8.0/lib/ddtrace/contrib/rails/framework.rb:16:in `<top (required)>'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ddtrace-0.8.0/lib/ddtrace.rb:31:in `require'
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ddtrace-0.8.0/lib/ddtrace.rb:31:in `<top (required)>'
```

example `application.rb`

```ruby
require_relative "boot"

require "rails"
# Pick the frameworks you want:
require "active_model/railtie"
# require "active_job/railtie"
# require "active_record/railtie"
require "action_controller/railtie"
# require "action_mailer/railtie"
require "action_view/railtie"
# require "action_cable/engine"
# require "sprockets/railtie"
# require "rails/test_unit/railtie"

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module TestApplication
  class Application < Rails::Application
    config.api_only = true
  end
end
```

**Comment by ufoot** [comment]
Thanks for reporting this. This sadly is a reintroduced bug (see https://github.com/DataDog/dd-trace-rb/commit/225074d10e672c458a9283c08f05c412b93a2da7 ) however this https://github.com/DataDog/dd-trace-rb/commit/68b130d8ce3bf6bb0d0f26f2cb41b6cac6404cb5 should fix it and the good news is this is scheduled for release `0.8.1`, coming soon.

**Comment by ufoot** [comment]
Should really be fixed by https://github.com/DataDog/dd-trace-rb/releases/tag/v0.8.1
