### ISSUE TITLE
Test failures with graphql gem 1.13 series

### ISSUE THREAD

**Issue by ivoanjo** [DataDog/dd-trace-rb#1866]
While investigating a different issue, I upgraded the graphql gem used for integration testing (to version `1.13.6`) and two tests started failing:

```
$ bundle exec rspec ./spec/ddtrace/contrib/graphql/tracer_spec.rb
All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 19633

GraphQL patcher
  class-based schema
    behaves like Schema patcher
      query trace
        is expected to equal nil (FAILED - 1)
      execution strategy
        matches expected strategy
  .define-style schema
    behaves like Schema patcher
      execution strategy
        matches expected strategy
      query trace
        example at ./spec/ddtrace/contrib/graphql/tracer_spec.rb:43 (FAILED - 2)

Failures:

  1) GraphQL patcher class-based schema behaves like Schema patcher query trace is expected to equal nil
     Failure/Error:
       spans.flatten.sort! do |a, b|
         if a.name == b.name
           if a.resource == b.resource
             if a.start_time == b.start_time
               a.end_time <=> b.end_time
             else
               a.start_time <=> b.start_time
             end
           else
             a.resource <=> b.resource

     ArgumentError:
       comparison of Datadog::Span with Datadog::Span failed
     Shared Example Group: "Schema patcher" called from ./spec/ddtrace/contrib/graphql/tracer_spec.rb:94
     # ./spec/ddtrace/contrib/support/tracer_helpers.rb:25:in `sort!'
     # etc...

  2) GraphQL patcher .define-style schema behaves like Schema patcher query trace
     Failure/Error: return_value = yield(span) if span || e.is_a?(StandardError)

     ArgumentError:
       wrong number of arguments (given 3, expected 2)
     Shared Example Group: "Schema patcher" called from ./spec/ddtrace/contrib/graphql/tracer_spec.rb:102
     # /Users/ivo.anjo/.rvm/gems/ruby-2.7.5/gems/graphql-1.13.6/lib/graphql/schema.rb:505:in `get_field'
     # etc...

Finished in 0.06868 seconds (files took 1.24 seconds to load)
4 examples, 2 failures

Failed examples:

rspec ./spec/ddtrace/contrib/graphql/tracer_spec.rb[1:1:1:2:1] # GraphQL patcher class-based schema behaves like Schema patcher query trace is expected to equal nil
rspec ./spec/ddtrace/contrib/graphql/tracer_spec.rb[1:2:1:2:1] # GraphQL patcher .define-style schema behaves like Schema patcher query trace
```

**Comment by ivoanjo** [comment]
I don't plan on investigating this for now, hopefully someone can pick it up.
