### ISSUE TITLE
Question: Is there an option to turn off logging in dd-trace-rb?

### ISSUE THREAD

**Issue by dominicfollett** [DataDog/dd-trace-rb#1962]
I am trying to reduce the amount of noise when running rspec tests, and I would like to disable the library's intrinsic logging during test execution. For example, I would like to prevent the following from being outputted during test runs:

```
E, [2022-04-04T16:35:51.785721 #54850] ERROR -- ddtrace: [ddtrace] (/Users/admin/.rvm/gems/ruby-2.7.4@myapp/gems/ddtrace-0.46.0/lib/ddtrace/transport/http/client.rb:35:in `rescue in send_request') Internal error during HTTP transport request. Cause: Failed to open TCP connection to 127.0.0.1:8126 (Connection refused - connect(2) for "127.0.0.1" port 8126) Location: /Users/admin/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/net/http.rb:960:in `initialize'
```

I have datadog configured like this:
```
if Rails.env.test?
    c.runtime_metrics.enabled = false
    c.diagnostics.debug = false
    c.diagnostics.health_metrics.enabled = false
    c.diagnostics.startup_logs.enabled = false
  end
end
```

Is there another option I can configure here for turning off logging completely?

**Comment by ivoanjo** [comment]
Hey @dominicfollett, glad you were able to figure it out!

I'll add two tiny suggestions:
* You can also disable tracing during tests, e.g. something like `c.tracer.enabled = !Rails.env.test?`. This way the logs you were seeing shouldn't come up (since the tracer will be operating in no-op mode).
* Your log message suggests that you're running a quite old version of the library (0.46.0), we suggest using the latest stable version, which currently is 0.54.2 (there's also a 1.0.0.beta1)

And don't hesitate to drop by with feedback/issues! :)

**Comment by rickyc** [comment]
It's now `c.tracing.enabled` instead of `c.tracer.enabled` in case anyone stumbles upon this in the future.

https://github.com/DataDog/dd-trace-rb/blob/e9dd04bef562545a01f768392ab7fd4ecaedfd51/docs/UpgradeGuide.md
