### ISSUE TITLE
ERROR -- ddtrace: [ddtrace] (/ddtrace-1.1.0/lib/datadog/tracing/contrib/action_pack/action_controller/instrumentation.rb:43:in `rescue in start_processing') undefined method `resource=' for nil:NilClass Did you mean?  rescue

### ISSUE THREAD

**Issue by key88sf** [DataDog/dd-trace-rb#2143]
**Current behaviour**
When running some specs, getting an error from the ddtrace gem:
E, [2022-07-09T22:59:16.464543 #42492] ERROR -- ddtrace: [ddtrace] (/Users/xxx/.rvm/gems/ruby-2.6.8@diaco/gems/ddtrace-1.1.0/lib/datadog/tracing/contrib/action_pack/action_controller/instrumentation.rb:43:in `rescue in start_processing') undefined method `resource=' for nil:NilClass
Did you mean?  rescue

**Expected behaviour**
No error should be output from the gem.

**Steps to reproduce**
I think just look at that line in the gem - there is probably a syntax error.

**How does `ddtrace` help you?**
We use it for our application tracing.

**Environment**

* **ddtrace version:** 1.1.0
* **Configuration block (`Datadog.configure ...`):**
* **Ruby version:** 2.6.8
* **Operating system:** Mac OS 12.4
* **Relevant library versions:**

**Comment by ivoanjo** [comment]
Hey @key88sf, thanks for the report!

I believe #2027 fixes this issue. I'm just preparing a new release (1.2.0) that will include this fix, and it should be out within the next few days.

**Comment by ivoanjo** [comment]
👋 @key88sf fix is now out in [v1.2.0](https://github.com/DataDog/dd-trace-rb/releases/tag/v1.2.0).
