### ISSUE TITLE
Sidekiq 7 support

### ISSUE THREAD

**Issue by kleinjm** [DataDog/dd-trace-rb#2446]
**Current behaviour**

When booting Sidekiq (7.0.1) via `bundle exec sidekiq`, I get the following error

```
super: no superclass method `redis_info' for Sidekiq:Module
Did you mean?  redis_pool
/Users/jklein/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/ddtrace-1.5.2/lib/datadog/tracing/contrib/sidekiq/server_internal_tracer/redis_info.rb:24:in `block in redis_info'
/Users/jklein/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/ddtrace-1.5.2/lib/datadog/tracing/tracer.rb:524:in `skip_trace'
/Users/jklein/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/ddtrace-1.5.2/lib/datadog/tracing/tracer.rb:139:in `trace'
/Users/jklein/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/ddtrace-1.5.2/lib/datadog/tracing.rb:18:in `trace'
/Users/jklein/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/ddtrace-1.5.2/lib/datadog/tracing/contrib/sidekiq/server_internal_tracer/redis_info.rb:13:in `redis_info'
/Users/jklein/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/sidekiq_unique_jobs.rb:201:in `fetch_redis_version'
/Users/jklein/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/config.rb:314:in `redis_version'
/Users/jklein/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/script/caller.rb:123:in `redis_version'
/Users/jklein/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/script/caller.rb:62:in `do_call'
/Users/jklein/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-unique-jobs-7.1.27/lib/sidekiq_unique_jobs/script/caller.rb:48:in `block in call_script'
/Users/jklein/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-7.0.1/lib/sidekiq/config.rb:156:in `block in redis'
```

**Expected behaviour**

Sidekiq boots

**Steps to reproduce**

Install gems in a Rails project
```
gem "ddtrace", require: "ddtrace/auto_instrument"
gem "sidekiq", "<8"
gem(
  "sidekiq-scheduler",
  git: "https://github.com/sidekiq-scheduler/sidekiq-scheduler",
  branch: "master", # necessary as the latest, unreleased version of this gem has Sidekiq 7 support
)
```

Run `bundle exec sidekiq`

**How does `ddtrace` help you?**

Great so far! We don't want to disabled sidekiq tracing in DD due to this issue.

**Environment**

* **ddtrace version:** 1.5.2
* **Configuration block (`Datadog.configure ...`):**

```rb
Datadog.configure do |c|
  tracing_enabled = ENV.fetch("DD_TRACING", false) == "true" || Rails.env.staging? || Rails.env.production?

  c.tracing.enabled = tracing_enabled

  c.tracing.instrument(:rails)
  c.tracing.instrument(
    :rack,
    headers: {
      request: %w[
        ACCEPT-LANGUAGE
        AUTHORIZATION
        PATCH-VERSION
        USER-AGENT
        X-FORWARDED-FOR
        X-FORWARDED-HOST
        X-REAL-IP
        X-REQUEST-ID
        X-REQUEST-START

      ],
      response: %w[
        CONTENT-LANGUAGE
        PATCH-VERSION
        RETRY-AFTER
        X-RATELIMIT-LIMIT
        X-RATELIMIT-REMAINING
        X-RATELIMIT-RESET
        X-REQUEST-ID
      ],
    },
    request_queuing: true,
    web_service_name: "nginx",
  )
  c.tracing.instrument(:redis)
  c.tracing.instrument(:sidekiq)

  c.tracing.log_injection = tracing_enabled

  # Ruby metrics tracking
  c.runtime_metrics.enabled = Rails.env.production?

  # AppSec tracking
  c.appsec.enabled = tracing_enabled && !Rails.env.test?
  c.appsec.instrument(:rails)

  c.ci.enabled = false
  # c.ci.instrument(:rspec)

  c.diagnostics.debug = false
  c.tracing.test_mode.enabled = false
end
```

* **Ruby version:** 3.1.2
* **Operating system:** MacOS 13.0 (22A380)
* **Relevant library versions:** (see above)

**Comment by kleinjm** [comment]
Never mind! This seems to be an issue with Sidekiq Unique Jobs not supporting Sidekiq 7 yet
https://github.com/mhenrixon/sidekiq-unique-jobs/issues/736
