### ISSUE TITLE
Uninitialized constant Datadog::Tracing::Contrib::Aws::Service

### ISSUE THREAD

**Issue by davidrunger-cl** [DataDog/dd-trace-rb#2894]
**Current behaviour**
An error message including `uninitialized constant Datadog::Tracing::Contrib::Aws::Service` is printed to stdout when we boot our Rails application that uses the `aws-sdk-s3` gem:
```
$ bundle exec rails console
E, [2023-06-03T22:59:19.522553 #77909] ERROR -- ddtrace: [ddtrace] (/Users/david/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ddtrace-1.12.0/lib/datadog/tracing/contrib/patcher.rb:51:in `on_patch_error') Failed to apply Datadog::Tracing::Contrib::Aws::Patcher patch. Cause: uninitialized constant Datadog::Tracing::Contrib::Aws::Service Location: /Users/david/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ddtrace-1.12.0/lib/datadog/tracing/contrib/aws/services.rb:118:in `<module:Aws>'
```

I speculate that also possibly DataDog monitoring of AWS services is impaired in some way, but I don't know that for a fact.

For context, the erroring line mentioned in that error message is [this line of code](https://github.com/DataDog/dd-trace-rb/blob/v1.12.0/lib/datadog/tracing/contrib/aws/services.rb#L118).

**Expected behaviour**
No error message is printed when booting the app.

**Steps to reproduce**

1. Create a file `ddtrace_bug_reproduction.rb` with the content below
1. Execute the file in your terminal with `ruby ddtrace_bug_reproduction.rb`
1. Observe that an error message is printed to your terminal; no error message should be printed

```rb
# file: ddtrace_bug_reproduction.rb
require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "aws-sdk-s3", "1.123.1"
  # if you change the ddtrace version to 1.11.1, the bug does not occur
  gem "ddtrace", "1.12.0", require: "ddtrace/auto_instrument"
  gem "rails", "7.0.5"
  gem "sqlite3", "1.6.3"
end

require "rails/all"
ENV['DATABASE_URL'] = "sqlite3:development.sqlite3"
ActiveRecord.legacy_connection_handling = false

class App < Rails::Application
  config.eager_load = false
end

App.initialize!
```

```
$ ruby ddtrace_bug_reproduction.rb
E, [2023-06-03T23:17:08.572470 #78192] ERROR -- ddtrace: [ddtrace] (/Users/david/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ddtrace-1.12.0/lib/datadog/tracing/contrib/patcher.rb:51:in `on_patch_error') Failed to apply Datadog::Tracing::Contrib::Aws::Patcher patch. Cause: uninitialized constant Datadog::Tracing::Contrib::Aws::Service Location: /Users/david/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ddtrace-1.12.0/lib/datadog/tracing/contrib/aws/services.rb:118:in `<module:Aws>'
```

**Environment**

* **ddtrace version:** 1.12.0
* **Configuration block (`Datadog.configure ...`):** not required to reproduce the bug
* **Ruby version:** 3.2.2
* **Operating system:** MacOS (arm64-darwin21)
* **Relevant library versions:** see gemfile in reproduction steps (which uses current latest versions of all gems)

**Comment by TonyCTHsu** [comment]
👋 @davidrunger-cl Thanks for reporting! I will take a look into this.
