### ISSUE TITLE
SIGTERM occured when server starting for falcon web server after dd-trace-rb v1.18.0

### ISSUE THREAD

**Issue by tmhrokmr** [DataDog/dd-trace-rb#3339]
**Current behaviour**

After v1.18.0, sigterm occurred.
``` ruby
/usr/local/bundle/gems/io-event-1.3.3/lib/io/event/support.rb:24: warning: IO::Buffer is experimental and both the Ruby and C interface may change in the future!
{"time":"2023-12-16T02:04:12+00:00","severity":"info","oid":2800,"pid":1,"subject":"Falcon::Command::Serve","message":"Falcon v0.42.3 taking flight! Using Async::Container::Forked {:count=>8}.\n- Binding to: #<Falcon::Endpoint http://0.0.0.0:4000/ {}>\n- To terminate: Ctrl-C or kill 1\n- To reload configuration: kill -HUP 1\n"}
{"time":"2023-12-16T02:04:12+00:00","severity":"info","oid":2840,"pid":1,"subject":"Falcon::Controller::Serve","message":"Starting Falcon Server on http://0.0.0.0:4000/"}
{"time":"2023-12-16T02:04:13+00:00","severity":"info","oid":3140,"pid":9,"subject":"Async::Container::Process::Instance","message":"- Per-process status: kill -USR1 9"}
{"time":"2023-12-16T02:04:13+00:00","severity":"info","oid":3180,"pid":10,"subject":"Async::Container::Process::Instance","message":"- Per-process status: kill -USR1 10"}
{"time":"2023-12-16T02:04:13+00:00","severity":"info","oid":3260,"pid":12,"subject":"Async::Container::Process::Instance","message":"- Per-process status: kill -USR1 12"}
{"time":"2023-12-16T02:04:13+00:00","severity":"info","oid":3100,"pid":8,"subject":"Async::Container::Process::Instance","message":"- Per-process status: kill -USR1 8"}
{"time":"2023-12-16T02:04:13+00:00","severity":"info","oid":3060,"pid":7,"subject":"Async::Container::Process::Instance","message":"- Per-process status: kill -USR1 7"}
{"time":"2023-12-16T02:04:13+00:00","severity":"info","oid":3220,"pid":11,"subject":"Async::Container::Process::Instance","message":"- Per-process status: kill -USR1 11"}
{"time":"2023-12-16T02:04:13+00:00","severity":"info","oid":3020,"pid":6,"subject":"Async::Container::Process::Instance","message":"- Per-process status: kill -USR1 6"}
{"time":"2023-12-16T02:04:13+00:00","severity":"info","oid":3300,"pid":13,"subject":"Async::Container::Process::Instance","message":"- Per-process status: kill -USR1 13"}
{"time":"2023-12-16T02:13:38+00:00","severity":"error","oid":3140,"pid":8,"subject":"Async::Container::Process","message":"SIGTERM","error":{"kind":"Async::Container::Terminate","message":"SIGTERM","stack":"/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:87:in `block (3 levels) in fork'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:240:in `select'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:240:in `run_once!'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:216:in `run_once'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:279:in `block in run'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:273:in `handle_interrupt'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:273:in `run'\n/usr/local/bundle/gems/async-2.6.4/lib/kernel/async.rb:32:in `Async'\n/usr/local/bundle/gems/falcon-0.42.3/lib/falcon/controller/serve.rb:87:in `block in setup'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:90:in `block (2 levels) in fork'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:85:in `fork'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:85:in `block in fork'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:121:in `initialize'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:84:in `new'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:84:in `fork'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/forked.rb:39:in `start'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/generic.rb:166:in `block in spawn'\n"}}
{"time":"2023-12-16T02:13:38+00:00","severity":"error","oid":3320,"pid":13,"subject":"Async::Container::Process","message":"SIGTERM","error":{"kind":"Async::Container::Terminate","message":"SIGTERM","stack":"/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:87:in `block (3 levels) in fork'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:240:in `select'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:240:in `run_once!'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:216:in `run_once'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:279:in `block in run'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:273:in `handle_interrupt'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:273:in `run'\n/usr/local/bundle/gems/async-2.6.4/lib/kernel/async.rb:32:in `Async'\n/usr/local/bundle/gems/falcon-0.42.3/lib/falcon/controller/serve.rb:87:in `block in setup'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:90:in `block (2 levels) in fork'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:85:in `fork'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:85:in `block in fork'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:121:in `initialize'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:84:in `new'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:84:in `fork'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/forked.rb:39:in `start'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/generic.rb:166:in `block in spawn'\n"}}
{"time":"2023-12-16T02:13:38+00:00","severity":"error","oid":3280,"pid":12,"subject":"Async::Container::Process","message":"SIGTERM","error":{"kind":"Async::Container::Terminate","message":"SIGTERM","stack":"/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:87:in `block (3 levels) in fork'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:240:in `select'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:240:in `run_once!'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:216:in `run_once'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:279:in `block in run'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:273:in `handle_interrupt'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:273:in `run'\n/usr/local/bundle/gems/async-2.6.4/lib/kernel/async.rb:32:in `Async'\n/usr/local/bundle/gems/falcon-0.42.3/lib/falcon/controller/serve.rb:87:in `block in setup'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:90:in `block (2 levels) in fork'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:85:in `fork'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:85:in `block in fork'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:121:in `initialize'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:84:in `new'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:84:in `fork'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/forked.rb:39:in `start'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/generic.rb:166:in `block in spawn'\n"}}
{"time":"2023-12-16T02:13:38+00:00","severity":"error","oid":3080,"pid":7,"subject":"Async::Container::Process","message":"SIGTERM","error":{"kind":"Async::Container::Terminate","message":"SIGTERM","stack":"/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:87:in `block (3 levels) in fork'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:240:in `select'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:240:in `run_once!'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:216:in `run_once'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:279:in `block in run'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:273:in `handle_interrupt'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:273:in `run'\n/usr/local/bundle/gems/async-2.6.4/lib/kernel/async.rb:32:in `Async'\n/usr/local/bundle/gems/falcon-0.42.3/lib/falcon/controller/serve.rb:87:in `block in setup'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:90:in `block (2 levels) in fork'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:85:in `fork'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:85:in `block in fork'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:121:in `initialize'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:84:in `new'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:84:in `fork'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/forked.rb:39:in `start'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/generic.rb:166:in `block in spawn'\n"}}
{"time":"2023-12-16T02:13:38+00:00","severity":"error","oid":3040,"pid":6,"subject":"Async::Container::Process","message":"SIGTERM","error":{"kind":"Async::Container::Terminate","message":"SIGTERM","stack":"/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:87:in `block (3 levels) in fork'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:240:in `select'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:240:in `run_once!'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:216:in `run_once'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:279:in `block in run'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:273:in `handle_interrupt'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:273:in `run'\n/usr/local/bundle/gems/async-2.6.4/lib/kernel/async.rb:32:in `Async'\n/usr/local/bundle/gems/falcon-0.42.3/lib/falcon/controller/serve.rb:87:in `block in setup'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:90:in `block (2 levels) in fork'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:85:in `fork'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:85:in `block in fork'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:121:in `initialize'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:84:in `new'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:84:in `fork'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/forked.rb:39:in `start'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/generic.rb:166:in `block in spawn'\n"}}
{"time":"2023-12-16T02:13:38+00:00","severity":"error","oid":3240,"pid":11,"subject":"Async::Container::Process","message":"SIGTERM","error":{"kind":"Async::Container::Terminate","message":"SIGTERM","stack":"/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:87:in `block (3 levels) in fork'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:240:in `select'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:240:in `run_once!'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:216:in `run_once'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:279:in `block in run'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:273:in `handle_interrupt'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:273:in `run'\n/usr/local/bundle/gems/async-2.6.4/lib/kernel/async.rb:32:in `Async'\n/usr/local/bundle/gems/falcon-0.42.3/lib/falcon/controller/serve.rb:87:in `block in setup'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:90:in `block (2 levels) in fork'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:85:in `fork'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:85:in `block in fork'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:121:in `initialize'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:84:in `new'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:84:in `fork'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/forked.rb:39:in `start'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/generic.rb:166:in `block in spawn'\n"}}
{"time":"2023-12-16T02:13:38+00:00","severity":"error","oid":3160,"pid":9,"subject":"Async::Container::Process","message":"SIGTERM","error":{"kind":"Async::Container::Terminate","message":"SIGTERM","stack":"/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:87:in `block (3 levels) in fork'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:240:in `select'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:240:in `run_once!'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:216:in `run_once'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:279:in `block in run'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:273:in `handle_interrupt'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:273:in `run'\n/usr/local/bundle/gems/async-2.6.4/lib/kernel/async.rb:32:in `Async'\n/usr/local/bundle/gems/falcon-0.42.3/lib/falcon/controller/serve.rb:87:in `block in setup'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:90:in `block (2 levels) in fork'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:85:in `fork'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:85:in `block in fork'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:121:in `initialize'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:84:in `new'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:84:in `fork'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/forked.rb:39:in `start'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/generic.rb:166:in `block in spawn'\n"}}
{"time":"2023-12-16T02:13:38+00:00","severity":"error","oid":3200,"pid":10,"subject":"Async::Container::Process","message":"SIGTERM","error":{"kind":"Async::Container::Terminate","message":"SIGTERM","stack":"/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:87:in `block (3 levels) in fork'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:240:in `select'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:240:in `run_once!'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:216:in `run_once'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:279:in `block in run'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:273:in `handle_interrupt'\n/usr/local/bundle/gems/async-2.6.4/lib/async/scheduler.rb:273:in `run'\n/usr/local/bundle/gems/async-2.6.4/lib/kernel/async.rb:32:in `Async'\n/usr/local/bundle/gems/falcon-0.42.3/lib/falcon/controller/serve.rb:87:in `block in setup'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:90:in `block (2 levels) in fork'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:85:in `fork'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:85:in `block in fork'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:121:in `initialize'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:84:in `new'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/process.rb:84:in `fork'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/forked.rb:39:in `start'\n/usr/local/bundle/gems/async-container-0.16.12/lib/async/container/generic.rb:166:in `block in spawn'\n"}}
{"time":"2023-12-16T02:13:38+00:00","severity":"error","oid":3180,"pid":1,"subject":"Async::Container::Forked","message":"pid 13 exit 1"}
{"time":"2023-12-16T02:13:38+00:00","severity":"error","oid":3180,"pid":1,"subject":"Async::Container::Forked","message":"pid 6 exit 1"}
{"time":"2023-12-16T02:13:38+00:00","severity":"error","oid":3180,"pid":1,"subject":"Async::Container::Forked","message":"pid 7 exit 1"}
{"time":"2023-12-16T02:13:38+00:00","severity":"error","oid":3180,"pid":1,"subject":"Async::Container::Forked","message":"pid 8 exit 1"}
{"time":"2023-12-16T02:13:38+00:00","severity":"error","oid":3180,"pid":1,"subject":"Async::Container::Forked","message":"pid 9 exit 1"}
{"time":"2023-12-16T02:13:38+00:00","severity":"error","oid":3180,"pid":1,"subject":"Async::Container::Forked","message":"pid 10 exit 1"}
{"time":"2023-12-16T02:13:38+00:00","severity":"error","oid":3180,"pid":1,"subject":"Async::Container::Forked","message":"pid 11 exit 1"}
{"time":"2023-12-16T02:13:38+00:00","severity":"error","oid":3180,"pid":1,"subject":"Async::Container::Forked","message":"pid 12 exit 1"}


```
**Expected behaviour**

before v1.17.0, sigterm does not occurred.

``` ruby
/usr/local/bundle/gems/io-event-1.3.3/lib/io/event/support.rb:24: warning: IO::Buffer is experimental and both the Ruby and C interface may change in the future!
{"time":"2023-12-16T02:27:20+00:00","severity":"info","oid":2800,"pid":1,"subject":"Falcon::Command::Serve","message":"Falcon v0.42.3 taking flight! Using Async::Container::Forked {:count=>8}.\n- Binding to: #<Falcon::Endpoint http://0.0.0.0:4000/ {}>\n- To terminate: Ctrl-C or kill 1\n- To reload configuration: kill -HUP 1\n"}
{"time":"2023-12-16T02:27:20+00:00","severity":"info","oid":2840,"pid":1,"subject":"Falcon::Controller::Serve","message":"Starting Falcon Server on http://0.0.0.0:4000/"}
{"time":"2023-12-16T02:27:21+00:00","severity":"info","oid":3140,"pid":10,"subject":"Async::Container::Process::Instance","message":"- Per-process status: kill -USR1 10"}
{"time":"2023-12-16T02:27:21+00:00","severity":"info","oid":3060,"pid":8,"subject":"Async::Container::Process::Instance","message":"- Per-process status: kill -USR1 8"}
{"time":"2023-12-16T02:27:21+00:00","severity":"info","oid":3220,"pid":12,"subject":"Async::Container::Process::Instance","message":"- Per-process status: kill -USR1 12"}
{"time":"2023-12-16T02:27:22+00:00","severity":"info","oid":3100,"pid":9,"subject":"Async::Container::Process::Instance","message":"- Per-process status: kill -USR1 9"}
{"time":"2023-12-16T02:27:22+00:00","severity":"info","oid":3260,"pid":13,"subject":"Async::Container::Process::Instance","message":"- Per-process status: kill -USR1 13"}
{"time":"2023-12-16T02:27:22+00:00","severity":"info","oid":3180,"pid":11,"subject":"Async::Container::Process::Instance","message":"- Per-process status: kill -USR1 11"}
{"time":"2023-12-16T02:27:22+00:00","severity":"info","oid":3020,"pid":7,"subject":"Async::Container::Process::Instance","message":"- Per-process status: kill -USR1 7"}
{"time":"2023-12-16T02:27:22+00:00","severity":"info","oid":3300,"pid":14,"subject":"Async::Container::Process::Instance","message":"- Per-process status: kill -USR1 14"}

```

**Steps to reproduce**

**How does `ddtrace` help you?**

**Environment**

* **ddtrace version:** v1.18.0
* **Configuration block (`Datadog.configure ...`):**
``` ruby
require "ddtrace"
Datadog.configure do |c|
  c.tracing.instrument :rack, service_name: "test"
end
use Datadog::Tracing::Contrib::Rack::TraceMiddleware

```
* **Ruby version:** 3.2.2
* **Operating system:** bookworm (ruby:3.2.2-slim-bookworm)
* **Relevant library versions:** falcon (0.42.3)

**Comment by ivoanjo** [comment]
Hey @tmhrokmr thanks for reaching out!

I've tried to reproduce it locally, and I wasn't unable to trigger the SIGTERM on v1.18.0.

I've also looked into the stack traces, and the `async-container` gem does seem to use signals (including `SIGTERM`) to manage its own termination. I wonder if this was related to some timeout?

Are you able to reproduce this issue on a minimal rack app [such as this one](https://cdragon.medium.com/what-is-ruby-rack-build-your-first-rack-app-32771cde34d9)?

**Comment by ivoanjo** [comment]
We haven't heard back from you in a while, so I'm going to close this ticket for now. Please do re-open and/or reach out to support if the issue shows up again (or if we can help in any way) :)

**Comment by tmhrokmr** [comment]
@ivoanjo I'm sorry for the delayed response. After updating to version 0.44 of Falcon, the errors have stopped occurring. Thank you very much.

**Comment by tmhrokmr** [comment]
Falcon 0.43

```
/usr/local/bundle/gems/io-event-1.5.1/lib/io/event/support.rb:27: warning: IO::Buffer is experimental and both the Ruby and C interface may change in the future!
{"time":"2024-04-10T07:22:58+00:00","severity":"info","oid":2700,"pid":1,"subject":"Falcon::Command::Serve","message":"Falcon v0.43.0 taking flight! Using Async::Container::Forked {:count=>8}.\n- Binding to: #<Falcon::Endpoint http://0.0.0.0:4000/ {}>\n- To terminate: Ctrl-C or kill 1\n- To reload configuration: kill -HUP 1\n"}
{"time":"2024-04-10T07:22:58+00:00","severity":"info","oid":2760,"pid":1,"subject":"Falcon::Controller::Serve","message":"Starting Falcon Server on http://0.0.0.0:4000/"}
{"time":"2024-04-10T07:22:58+00:00","severity":"info","oid":2920,"pid":10,"subject":"Async::Container::Process::Instance","message":"- Per-process status: kill -USR1 10"}
{"time":"2024-04-10T07:22:58+00:00","severity":"info","oid":2840,"pid":8,"subject":"Async::Container::Process::Instance","message":"- Per-process status: kill -USR1 8"}
{"time":"2024-04-10T07:22:58+00:00","severity":"info","oid":2880,"pid":9,"subject":"Async::Container::Process::Instance","message":"- Per-process status: kill -USR1 9"}
{"time":"2024-04-10T07:22:58+00:00","severity":"info","oid":3000,"pid":12,"subject":"Async::Container::Process::Instance","message":"- Per-process status: kill -USR1 12"}
{"time":"2024-04-10T07:22:58+00:00","severity":"info","oid":2960,"pid":11,"subject":"Async::Container::Process::Instance","message":"- Per-process status: kill -USR1 11"}
{"time":"2024-04-10T07:22:58+00:00","severity":"info","oid":3080,"pid":14,"subject":"Async::Container::Process::Instance","message":"- Per-process status: kill -USR1 14"}
{"time":"2024-04-10T07:22:58+00:00","severity":"info","oid":3040,"pid":13,"subject":"Async::Container::Process::Instance","message":"- Per-process status: kill -USR1 13"}
{"time":"2024-04-10T07:22:58+00:00","severity":"info","oid":2800,"pid":7,"subject":"Async::Container::Process::Instance","message":"- Per-process status: kill -USR1 7"}


```
Falcon 0.44
```
/usr/local/bundle/gems/io-event-1.5.1/lib/io/event/support.rb:27: warning: IO::Buffer is experimental and both the Ruby and C interface may change in the future!
{"time":"2024-04-10T07:21:00+00:00","severity":"info","oid":2700,"pid":1,"subject":"Falcon::Command::Serve","message":"Falcon v0.44.0 taking flight! Using Async::Container::Forked {:count=>8}.\n- Binding to: #<Falcon::Endpoint http://0.0.0.0:4000/ {}>\n- To terminate: Ctrl-C or kill 1\n- To reload configuration: kill -HUP 1\n"}
{"time":"2024-04-10T07:21:00+00:00","severity":"info","oid":2760,"pid":1,"subject":"Falcon::Service::Server","message":"Starting server on #<Falcon::Endpoint http://0.0.0.0:4000/ {}>"}



```

**Comment by ivoanjo** [comment]
Awesome to know! Out of curiosity [I checked the diff between Falcon releases](https://github.com/socketry/falcon/compare/v0.43.0...v0.44.0) and it's not clear what might've fixed it (I wonder if the fix was in one of its dependencies?). A mystery indeed :)
