### ISSUE TITLE
Rails instrumentation fails with distributed_tracing=false

### ISSUE THREAD

**Issue by stac47** [DataDog/dd-trace-rb#3389]
**Current behaviour**

When I set the `rails` integration as follow (without distributed tracing):
```
Datadog.configure do |c|
  c.tracing.enabled = Rails.env.production?
  c.tracing.instrument :rails, { distributed_tracing: false }
end
```

And I run the spec, I got this:
```
% bundle exec rspec spec/requests/items_spec.rb
F

Failures:

  1) Items GET /index shows all the items
     Failure/Error: get items_path

     NoMethodError:
       undefined method `resource_override?' for nil
     # /Users/lstacul/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/ddtrace-1.19.0/lib/datadog/tracing/contrib/rack/middlewares.rb:161:in `set_request_tags!'
     # /Users/lstacul/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/ddtrace-1.19.0/lib/datadog/tracing/contrib/rack/middlewares.rb:127:in `call'
     # /Users/lstacul/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/railties-7.1.3/lib/rails/engine.rb:536:in `call'
     # /Users/lstacul/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rack-test-2.1.0/lib/rack/test.rb:360:in `process_request'
     # /Users/lstacul/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rack-test-2.1.0/lib/rack/test.rb:153:in `request'
```
I am using the latest of Ruby, Rails and `ddtrace` and I created a reproducer https://github.com/stac47/reproducer-dd

**Expected behaviour**

I would expect the test not to be interrupted by the `rack` Datadog middleware when I run the tests.

**Steps to reproduce**

* `git clone https://github.com/stac47/reproducer-dd`
* Go into the cloned repository and `bundle`
* Run the test: `bundle exec rspec spec/requests/items_spec.rb`

Note that if you run the server with `rails s` and try to access `http://localhost:3000/items` you will have this on your browser:
```
Puma caught this error: undefined method `resource_override?' for nil (NoMethodError)
/Users/lstacul/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/ddtrace-1.19.0/lib/datadog/tracing/contrib/rack/middlewares.rb:161:in `set_request_tags!'
/Users/lstacul/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/ddtrace-1.19.0/lib/datadog/tracing/contrib/rack/middlewares.rb:127:in `call'
/Users/lstacul/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/railties-7.1.3/lib/rails/engine.rb:536:in `call'
/Users/lstacul/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/puma/configuration.rb:272:in `call'
/Users/lstacul/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/puma/request.rb:100:in `block in handle_request'
/Users/lstacul/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/puma/thread_pool.rb:378:in `with_force_shutdown'
/Users/lstacul/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/puma/request.rb:99:in `handle_request'
/Users/lstacul/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/puma/server.rb:464:in `process_client'
/Users/lstacul/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/puma/server.rb:245:in `block in run'
/Users/lstacul/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/puma/thread_pool.rb:155:in `block in spawn_thread'
```

And in the console logs:

```
2024-01-20 16:50:38 +0100 Rack app ("GET /items" - (127.0.0.1)): #<NoMethodError: undefined method `resource_override?' for nil>
```

**Environment**

* **ddtrace version:** 1.19.0
* **Configuration block (`Datadog.configure ...`):** See above
* **Ruby version:** 3.3.0
* **Operating system:** MacOS
* **Relevant library versions:** Rails 7.1.3
Note: I can reproduce this error on Ruby 2.7.8 and Rails 4.2.11.

**Comment by delner** [comment]
Hey @stac47! Thanks for reporting. I will pass this by the team, see if we can reproduce this.

Do you have an example of the request you're sending to the app? A `curl` command perhaps?

**Comment by stac47** [comment]
Thanks for your answer.

```
% curl http://localhost:3000/items
Puma caught this error: undefined method `resource_override?' for nil (NoMethodError)
/Users/lstacul/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/ddtrace-1.19.0/lib/datadog/tracing/contrib/rack/middlewares.rb:161:in `set_request_tags!'
/Users/lstacul/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/ddtrace-1.19.0/lib/datadog/tracing/contrib/rack/middlewares.rb:127:in `call'
/Users/lstacul/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/railties-7.1.3/lib/rails/engine.rb:536:in `call'
/Users/lstacul/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/puma/configuration.rb:272:in `call'
/Users/lstacul/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/puma/request.rb:100:in `block in handle_request'
/Users/lstacul/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/puma/thread_pool.rb:378:in `with_force_shutdown'
/Users/lstacul/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/puma/request.rb:99:in `handle_request'
/Users/lstacul/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/puma/server.rb:464:in `process_client'
/Users/lstacul/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/puma/server.rb:245:in `block in run'
/Users/lstacul/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/puma/thread_pool.rb:155:in `block in spawn_thread'%
```

**Comment by TonyCTHsu** [comment]
@stac47 Thanks for reporting and the reproducible app! 

I will address that 😄

**Comment by TonyCTHsu** [comment]
👋 @stac47 , `1.20.0` has been released! Give it a try 👍

**Comment by stac47** [comment]
Ah ah, I was about to tell you the patch is working fine :D . Happy to go with the new version. Thanks for your help.
