### ISSUE TITLE
AWS integration fails to start with "conflicting" classname

### ISSUE THREAD

**Issue by joffotron** [DataDog/dd-trace-rb#373]
Hi, with the 0.12.0.beta2 gem, our rails app will not boot with the AWS integration enabled:

We get the following error:

```
backend_1      | rake aborted!
backend_1      | LoadError: Unable to autoload constant KMS, expected /app/app/services/raisebook_aws/kms.rb to define it
backend_1      | /usr/local/bundle/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:512:in `load_missing_constant'
backend_1      | /usr/local/bundle/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:43:in `load_missing_constant'
backend_1      | /usr/local/bundle/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:202:in `const_missing'
backend_1      | /usr/local/bundle/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:543:in `load_missing_constant'
backend_1      | /usr/local/bundle/gems/bootsnap-1.1.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:43:in `load_missing_constant'
backend_1      | /usr/local/bundle/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:202:in `const_missing'
backend_1      | /usr/local/bundle/gems/ddtrace-0.12.0.beta2/lib/ddtrace/contrib/aws/patcher.rb:52:in `const_get'
backend_1      | /usr/local/bundle/gems/ddtrace-0.12.0.beta2/lib/ddtrace/contrib/aws/patcher.rb:52:in `block in loaded_constants'
backend_1      | /usr/local/bundle/gems/ddtrace-0.12.0.beta2/lib/ddtrace/contrib/aws/patcher.rb:50:in `each'
backend_1      | /usr/local/bundle/gems/ddtrace-0.12.0.beta2/lib/ddtrace/contrib/aws/patcher.rb:50:in `each_with_object'
backend_1      | /usr/local/bundle/gems/ddtrace-0.12.0.beta2/lib/ddtrace/contrib/aws/patcher.rb:50:in `loaded_constants'
backend_1      | /usr/local/bundle/gems/ddtrace-0.12.0.beta2/lib/ddtrace/contrib/aws/patcher.rb:25:in `patch'
backend_1      | /usr/local/bundle/gems/ddtrace-0.12.0.beta2/lib/ddtrace/configuration.rb:27:in `use'
backend_1      | /app/config/initializers/datadog.rb:3:in `block in <main>'
backend_1      | /usr/local/bundle/gems/ddtrace-0.12.0.beta2/lib/ddtrace.rb:47:in `configure'
backend_1      | /app/config/initializers/datadog.rb:1:in `<main>'
....
```

In our code, we have 

/app/app/services/raisebook_aws/kms.rb:
```ruby
require 'aws-sdk-kms'
require 'base64'

module RaisebookAws
  class KMS
  ...
```

Which is in an entirely separate module.  Looks like an issue with how the constants are loaded in the ddtrace patcher?

**Comment by delner** [comment]
I'm not sure yet why it's at all trying to load that class. My first suspicion, if I had to start somewhere, would be the Rails ActiveSupport autoload magic and perhaps order of load paths for constants. Would need a deeper investigation before we could be sure.

@joffotron Can you provide a very minimal Rails app or set of code samples that replicate the problem?

**Comment by joffotron** [comment]
@delner Update: I set up a clean Rails app with the offending code included, but so far haven't been able to reproduce :( 

I'll keep digging!

**Comment by delner** [comment]
Okay no problem, let me know what you find.
