### ISSUE TITLE
Failed to apply Datadog::Contrib::Rake::Patcher 

### ISSUE THREAD

**Issue by mustela** [DataDog/dd-trace-rb#923]
Hey guys, Im having the following error and I couldn't find anything around it.

```
15/01/2020 09:54:11E, [2020-01-15T08:54:11.818714 #30] ERROR -- ddtrace: [ddtrace] (/home/my-app/api/vendor/bundle/ruby/2.5.0/gems/ddtrace-0.31.0/lib/ddtrace/contrib/patcher.rb:35:in `rescue in block in patch') Failed to apply Datadog::Contrib::Rake::Patcher patch. Cause: uninitialized constant Rake::Task Location: /home/my-app/api/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:79:in `block in load_missing_constant'
15/01/2020 09:54:12* Listening on tcp://0.0.0.0:3000
```
Im using `ruby:2.5.7` and `rails 5.2.4.1`

The config I have is 
```
Datadog.configure do |c|
  c.tracer enabled: true
  c.analytics_enabled = true
  c.tracer tags: { 'env' => Rails.env }
  c.use :rails
  c.use :rake
end

```

**Comment by mustela** [comment]
Ive remove bootsnap and what Im having is  
```
15/01/2020 11:19:02E, [2020-01-15T10:19:02.254616 #30] ERROR -- ddtrace: [ddtrace] (/home/my-app/api/vendor/bundle/ruby/2.5.0/gems/ddtrace-0.31.0/lib/ddtrace/contrib/patcher.rb:35:in `rescue in block in patch') Failed to apply Datadog::Contrib::Rake::Patcher patch. Cause: uninitialized constant Rake::Task Location: /home/my-app/api/vendor/bundle/ruby/2.5.0/gems/ddtrace-0.31.0/lib/ddtrace/contrib/rake/patcher.rb:21:in `patch'
15/01/2020 11:19:03* Listening on tcp://0.0.0.0:3000
```

**Comment by mustela** [comment]
It seems that adding `require 'rake'` to the initialisation file, did the trick.
